### ISSUE TITLE
[Purchases] - ERROR: 🍎‼️ There was a problem with the App Store.

### ISSUE THREAD

**Issue by thanhnhan111093** [RevenueCat/purchases-flutter#394] opened 2022-07-12 10:45 UTC
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

Step reproduce
1. Login user id A
2. Make purchase with package PA
3. Logout user-id A
4. Login into user-id B with the same app store account
5. Make purchase with package PA

-> Sometime purchasePackage will throw error "There was a problem with the App Store."

Note: We were rejected by apple because of this error 

https://1drv.ms/v/s!AvJkkiWzYFLZgepf71V0IqFFsxtY2g?e=ypN2rT

**Comment by vegaro** [comment] 2022-07-12 10:54
Hi @thanhnhan111093 , since both users have the same app store account it is expected that the purchase fails since that app store account is already subscribed. 

Regarding being rejected by Apple because of this error, I would recommend trying to build a new build and submitting again. Their sandbox environment is notoriously flaky and it's very common to have to submit multiple times to get approved. To give an example of this, take a look at this other issue https://github.com/RevenueCat/purchases-flutter/issues/204

**Comment by thanhnhan111093** [comment] 2022-07-12 11:01
We have uploaded more than 10 versions for this bug. I don't think the build for them to review is the best

**Comment by thanhnhan111093** [comment] 2022-07-12 11:06
> since both users have the same app store account it is expected that the purchase fails since that app store account is already subscribed.

I'm aware of it, but we need to have a sensible message instead of "There was problem from the App Store"

**Comment by thanhnhan111093** [comment] 2022-07-15 02:25
i tried get the log from apple reviewer, the retry subscription 6 time, all of them throw error: 
{log} {2022-07-13 03:13:00.086000} {SubscriptionHelper} {paymentMultiSubscription: can't make payment PlatformException errorCode PurchasesErrorCode.storeProblemError 2 -> There was a problem with the App Store.} {LogLevel.INFO}

**Comment by vegaro** [comment] 2022-07-15 10:09
Hmmm that's interesting... Can you see if they are trying with different users in their logs?

Apart from that, have you tried with a brand new sandbox account? Does your app grant the premium plan after an initial successful purchase? Or do purchases always fail? 

I have to say that I have tried to reproduce this locally and strangely enough, I don't get any error after the "You're currently subscribed to this" dialog. Storekit is sending a success in that case which is not what you see. @aboedo filed a radar last week because he was sometimes seeing a success and sometimes an error, but I am now only seeing success. I wonder if they have changed something in sandbox.

**Comment by thanhnhan111093** [comment] 2022-07-15 14:09
They only use the 1 account we provide, but not sure if they use the brand new sandbox account. They tried to buy 6 times with one pack and all of them failed.

**Comment by beylmk** [comment] 2022-07-18 15:16
@thanhnhan111093 hey 👋 just want to clarify a point on your last comment `They tried to buy 6 times with one pack and all of them failed`... so you're saying even the initial purchase errors? So steps to reproduce would just be any initial purchase? 

Thanks for answering all our questions, just want to be sure we're investigating the most relevant code...

**Comment by thanhnhan111093** [comment] 2022-07-20 03:49
> 



> @thanhnhan111093 hey 👋 just want to clarify a point on your last comment `They tried to buy 6 times with one pack and all of them failed`... so you're saying even the initial purchase errors? So steps to reproduce would just be any initial purchase?
> 
> Also, can you please confirm the version of the sdk that you're on?
> 
> Thanks for answering all our questions, just want to be sure we're investigating the most relevant code...

These logs we tried to get from the apple reviewer, so we're not sure what the steps they took to make it either. We tried to reproduce it but there was only one case like the video. 
**NOTE:** Before submitting we have checked all subscriptions to the review account have expired.
From the log, it shows login succeed and trying to buy their monthly package.


We are using SDK: purchases_flutter: ^3.10.0

**Comment by beylmk** [comment] 2022-07-21 22:29
Hey @thanhnhan111093 given you have a number of issues open, I'm wondering if a Zoom call might be more effective. I have a feeling they're all related. I'm going to shoot you an email to the email on your Github for scheduling.

**Comment by thanhnhan111093** [comment] 2022-07-22 02:58
sorry, my english is not good, so we should keep this channel

**Comment by beylmk** [comment] 2022-07-22 14:39
Okay no problem. I'll look back into all 3 issues this afternoon. Thanks for your patience, I really hope we can get this figured out for you!

**Comment by beylmk** [comment] 2022-07-27 14:42
Closing as user reported the app was accepted.

**Closed by beylmk** 2022-07-27 14:42 UTC
Labels: bug
