### ISSUE TITLE
Calling Purchases.getOfferings(); in purchases_flutter: ^3.9.0 results in  "The method 'toDouble' was called on null." error

### ISSUE THREAD

**Issue by KubaStachecki** [RevenueCat/purchases-flutter#293] opened 2022-01-14 13:21 UTC
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [X] I have searched the [Community](https://community.revenuecat.com)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. **Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

PROBLEM DESCRIPTION:

Calling Purchases.getOfferings(); in purchases_flutter: ^3.9.0 results in  "The method 'toDouble' was called on null." error and returns null on Android (IOS version that utilises the same Flutter code builds and works correctly). Tested on real devices, with both debug and release builds.

The same Play Store configuration and Flutter code works flawlessly on previous app version (built with purchases_flutter 3.8.0) in production app. Problem started after updating to 3.9.0 without additional changes.

Product descriptions, prices and details are described correctly in the log (although I removed details in here), but "Requesting products from the store with identifiers" is happening a couple times every app start, even thought I'm calling Purchases.setup(apiKey, appUserId: uid); only once.

1. Environment
   1. Output of `flutter doctor`
   2. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

Code used to initialise Purchases:

  Future<void> initPlatformState() async {
    await Purchases.setDebugLogsEnabled(kDebugMode);
    String apiKey = Platform.isAndroid ? Constants.revenueCatApiKeyAndroid : Constants.revenueCatApiKeyIOS;

    await Purchases.setup(apiKey, appUserId: uid);
    
    try {
      purchaserInfo = await Purchases.getPurchaserInfo();
    } on PlatformException catch (e) {
      // Error fetching purchaser info
      print('------ error getting purchaser info ------');
      print(e.code);
      print(e.message);
    }

    try {
      offerings = await Purchases.getOfferings();
    } on PlatformException catch (e) {
      // Error fetching offerings info
      print('------ error getting offerings list ------');
      print(e.code);
      print(e.message);
    }
    
  }

Exact error:

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
NoSuchMethodError: The method 'toDouble' was called on null. Receiver: null Tried calling: toDouble(). Error thrown null.

._$$_IntroductoryPriceFromJson (introductory_price.g.dart:11)
new _$_IntroductoryPrice.fromJson (introductory_price.freezed.dart:247)
._$IntroductoryPriceFromJson (introductory_price.freezed.dart:17)
new IntroductoryPrice.fromJson (introductory_price.dart:48)
._$$_ProductFromJson (product_wrapper.g.dart:18)
new _$_Product.fromJson (product_wrapper.freezed.dart:291)
._$ProductFromJson (product_wrapper.freezed.dart:17)
new Product.fromJson (product_wrapper.dart:41)
._$$_PackageFromJson (package_wrapper.g.dart:13)
new _$_Package.fromJson (package_wrapper.freezed.dart:203)
._$PackageFromJson (package_wrapper.freezed.dart:17)
new Package.fromJson (package_wrapper.dart:76)
_$$_OfferingFromJson.<fn> (offering_wrapper.g.dart:13)
SetMixin.toList (dart:collection)
._$$_OfferingFromJson (offering_wrapper.g.dart:14)
new _$_Offering.fromJson (offering_wrapper.freezed.dart:390)
._$OfferingFromJson (offering_wrapper.freezed.dart:17)
new Offering.fromJson (offering_wrapper.dart:52)
_$$_OfferingsFromJson.<fn> (offerings_wrapper.g.dart:12)
MapMixin.map (dart:collection)
._$$_OfferingsFromJson (offerings_wrapper.g.dart:10)
new _$_Offerings.fromJson (offerings_wrapper.freezed.dart:153)
._$OfferingsFromJson (offerings_wrapper.freezed.dart:17)
new Offerings.fromJson (offerings_wrapper.dart:26)
Purchases.getOfferings (purchases_flutter.dart:141)
PurchasesService.initPlatformState (revcat_purchases_service.dart:54)

Purchases debug log:

D/[Purchases] - DEBUG( 8772): ℹ️ Debug logging enabled
D/[Purchases] - DEBUG( 8772): ℹ️ SDK Version - 4.6.0
D/[Purchases] - DEBUG( 8772): 👤 Initial App User ID - *******
D/[Purchases] - DEBUG( 8772): 👤 Identifying App User ID: ******
D/[Purchases] - DEBUG( 8772): ℹ️ Deleting old synced subscriber attributes that don't belong to ******
D/[Purchases] - DEBUG( 8772): ℹ️ App foregrounded
D/[Purchases] - DEBUG( 8772): ℹ️ PurchaserInfo cache is stale, updating from network in foreground.
D/[Purchases] - DEBUG( 8772): ℹ️ Offerings cache is stale, updating from network in foreground
D/[Purchases] - DEBUG( 8772): 😻 Offerings updated from network.
D/[Purchases] - DEBUG( 8772): ℹ️ Skipping updating pending purchase queue since BillingClient is not connected yet.
D/[Purchases] - DEBUG( 8772): ℹ️ No subscriber attributes to synchronize.
D/[Purchases] - DEBUG( 8772): ℹ️ Listener set
D/[Purchases] - DEBUG( 8772): ℹ️ Sending latest PurchaserInfo to listener.
D/[Purchases] - DEBUG( 8772): ℹ️ Starting connection for com.android.billingclient.api.BillingClientImpl@4d010c4
D/[Purchases] - DEBUG( 8772): ℹ️ Billing Service Setup finished for com.android.billingclient.api.BillingClientImpl@4d010c4
D/[Purchases] - DEBUG( 8772): ℹ️ Updating pending purchase queue
D/[Purchases] - DEBUG( 8772): ℹ️ Vending PurchaserInfo from cache.
D/[Purchases] - DEBUG( 8772): ℹ️ Checking if cache is stale AppInBackground false
D/[Purchases] - DEBUG( 8772): ℹ️ No cached Offerings, fetching from network
D/[Purchases] - DEBUG( 8772): Same call already in progress, adding to callbacks map with key: /subscribers/*****/offerings
D/[Purchases] - DEBUG( 8772): ℹ️ Vending PurchaserInfo from cache.
D/[Purchases] - DEBUG( 8772): ℹ️ Checking if cache is stale AppInBackground false
D/[Purchases] - DEBUG( 8772): ℹ️ API request started: GET /subscribers/*****
D/[Purchases] - DEBUG( 8772): ℹ️ API request completed with status: GET /subscribers/****** 304
D/[Purchases] - DEBUG( 8772): ℹ️ PurchaserInfo updated, sending to listener.
D/[Purchases] - DEBUG( 8772): ℹ️ API request started: GET /subscribers/******/offerings
D/[Purchases] - DEBUG( 8772): ℹ️ API request completed with status: GET /subscribers/*******/offerings 304
D/[Purchases] - DEBUG( 8772): ℹ️ Requesting products from the store with identifiers: (correct list of identifiers)
D/[Purchases] - DEBUG( 8772): ℹ️ Requesting products from the store with identifiers: (correct list of identifiers)
D/[Purchases] - DEBUG( 8772): ℹ️ Querying purchases
D/[Purchases] - DEBUG( 8772): ℹ️ Cleaning previously sent tokens
D/[Purchases] - DEBUG( 8772): ℹ️ Tokens already posted: []
D/[Purchases] - DEBUG( 8772): ℹ️ Saving tokens []
D/[Purchases] - DEBUG( 8772): ℹ️ Tokens already posted: []
D/[Purchases] - DEBUG( 8772): ℹ️ Products request finished for (correct list of identifiers)
D/[Purchases] - DEBUG( 8772): 💰 Retrieved skuDetailsList: SkuDetails:******
D/[Purchases] - DEBUG( 8772): ℹ️ Requesting products from the store with identifiers: (correct list of identifiers)
D/[Purchases] - DEBUG( 8772): ℹ️ Products request finished for ****
D/[Purchases] - DEBUG( 8772): 💰 Retrieved skuDetailsList: SkuDetails: ****

Flutter Doctor:

[✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.8.1 at /Users/kuba/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

**Additional context**

**Comment by NatsuOnFire** [comment] 2022-01-14 13:44
Same, I have this error with the new version : 

```
I/flutter (27464): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (27464): type 'Null' is not a subtype of type 'num' in type cast
I/flutter (27464): #0      _$$_IntroductoryPriceFromJson (package:purchases_flutter/models/introductory_price.g.dart:11:22)
I/flutter (27464): #1      new _$_IntroductoryPrice.fromJson (package:purchases_flutter/models/introductory_price.freezed.dart:247:7)
I/flutter (27464): #2      _$IntroductoryPriceFromJson (package:purchases_flutter/models/introductory_price.freezed.dart:17:29)
I/flutter (27464): #3      new IntroductoryPrice.fromJson (package:purchases_flutter/models/introductory_price.dart:48:7)
I/flutter (27464): #4      _$$_ProductFromJson (package:purchases_flutter/models/product_wrapper.g.dart:18:31)
I/flutter (27464): #5      new _$_Product.fromJson (package:purchases_flutter/models/product_wrapper.freezed.dart:291:7)
I/flutter (27464): #6      _$ProductFromJson (package:purchases_flutter/models/product_wrapper.freezed.dart:17:19)
I/flutter (27464): #7      new Product.fromJson (package:purchases_flutter/models/product_wrapper.dart:41:7)
I/flutter (27464): #8      _$$_PackageFromJson (package:purchases_flutter/models/package_wrapper.g.dart:13:15)
I/flutter (27464): #9      new _$_Package.fromJson (package:purchases_flutter/models/package_wrapper.freezed.dart:203:7)
I/flutter (27464): #10     _$Packag
I/flutter (27464): ----------------------------------------------------
```

**Comment by mtalha101** [comment] 2022-01-14 14:51
I was able to figure out a little bit of this issue. This issue is caused due to Introductory Price of Consumables. The Object of Introductory Price for consumables, if contains null values, gives a NoSuchMethodException in fromJson method. The 'price' key in json casted as num, uses extension 'toDouble()' at the end., if this key i.e. 'price', is null, the 'toDouble()' extension gets a null value and gives exception.

The problem is in introductory_price.g.dart fromJson method.

**Comment by aboedo** [comment] 2022-01-14 14:57
agreed. The underlying issue seems to be an inconsistency between iOS and Android implementations in purchases-hybrid-common, where a null intro price would get transformed into a dictionary of null values in Android, and a single, null value in iOS. I'm working on a fix.

**Comment by NatsuOnFire** [comment] 2022-01-14 16:03
@aboedo 
But why do we end up with a null result in version 3.9.0 and not in version 3.8.0?
Aren't we supposed to fetch offers instead of null, is this related to the problem?

**Comment by aboedo** [comment] 2022-01-14 17:02
In 3.9.0, our models were refactored to use [freezed](https://pub.dev/packages/freezed) for serialization, and the freezed code didn't take into account the two possible implementations. 
3.8.0 and earlier used a different key for parsing intro prices, and that key wasn't affected by the bug.

**Comment by aboedo** [comment] 2022-01-14 17:06
to be clear, the problem is entirely internal parsing, so your usage of the SDK is probably fine

**Comment by aboedo** [comment] 2022-01-14 20:40
Fixed in https://github.com/RevenueCat/purchases-flutter/pull/294/, will make a release when that gets approved. Thanks again everyone!!!

**Closed** 2022-01-17 12:37 UTC
Labels: bug
