### ISSUE TITLE
Purchases.logOut() crashing the iOS App

### ISSUE THREAD

**Issue by knightowlRaising** [RevenueCat/purchases-flutter#241] opened 2021-09-08 08:17 UTC
After doing Purchases.logOut() the iOS app is getting crashed.

**Comment by aboedo** [comment] 2021-09-08 18:01
hi @knightowlRaising, thanks for reporting! 
Could you provide us more details so we can try to reproduce and investigate? 
in particular, could you provide us:
- a stack trace, error message
- debug logs
- the output of `flutter doctor`

**Comment by vegaro** [comment] 2021-10-04 21:53
I am going to be closing this since there's no answer. Feel free to reopen if you come up with more info we can use to replicate the issue. Thanks!

**Closed by vegaro** 2021-10-04 21:53 UTC
Labels: bug

**Comment by aboedo** [comment] 2021-10-12 20:27
@AhmedNourJamalElDin you only need to call `Purchases.setup` once in the app's entire lifetime, and you should try to call it as soon as possible (i.e.: when the app launches). This is because if there are any transactions in the queue, the SDK needs to know right away to ensure that the user isn't kept waiting for their purchases to go through. 
If the user hasn't logged in by the time you call `setup`, you can call `setup` without an `appUserID`, and then set it using `logIn` after the user logs in. 

So my advice would be to make sure it gets called right away, and then you can safely call `logOut` and `logIn` when needed. 

Hope this helps!

**Comment by AhmedNourJamalElDin** [comment] 2021-10-13 06:37
Hello @aboedo 

Thank you so much.

Yea, I know all of these but unfortunately my app is for Kids and I am not sure Apple will allow us to connect to RevenueCat at the launching (starting) of the app but it allows such thing after passing the parental gate.

I have added some flag to handle this issue for me but I wanted to know if there is a better way.

**Comment by aboedo** [comment] 2021-10-13 19:33
@AhmedNourJamalElDin 
There shouldn't be any issues with Kids apps using RevenueCat. Several kids apps are using RevenueCat already. 
Just make sure that you're: 
- Not including the `AdSupport` framework
- Not including any kind of analytics frameworks / plugins
- Not using the `automaticSearchAdsCollection` feature in RevenueCat (it's disabled by default). 

If you're doing all of the above, you should be able to set up our SDK at any point in the app lifecycle, ideally as early as possible.
