### ISSUE TITLE
Purchases.getOfferings() not working on IOS production mode

### ISSUE THREAD

**Issue by maziarit** [RevenueCat/purchases-flutter#229] opened 2021-08-07 13:53 UTC
My application completely working on debug mode (Simulator and Real device).
But when I publish on App store Purchases.getOfferings() is null

**Comment by aboedo** [comment] 2021-08-09 14:08
Hi @maziarit! 👋 

This is most likely a configuration issue, and can be caused by a few things. Here's an [article from our support docs that may be helpful](https://community.revenuecat.com/sdks-51/why-are-products-empty-124). It includes a few steps to fix the issue. 

We reserve GitHub issues for bug reports only, the best way to get support for this kind of issue is through our Community at https://community.revenuecat.com. 

I'm tentatively closing this out, since it's most likely not caused by a bug. 

Have a great day!

**Closed by aboedo** 2021-08-09 14:08 UTC
Labels: bug
