### ISSUE TITLE
Can't re-subscribe on iOS.

### ISSUE THREAD

**Issue by ecorradini** [RevenueCat/purchases-flutter#308] opened 2022-01-23 13:26 UTC
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [X] I have searched the [Community](https://community.revenuecat.com)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
Once disabled a subscription of a subscription group from the App Store page, I am not able to subscribe again to any of the group. I have to uninstall and reinstall the app to re-subscribe. I do not understand if it's a correct behavior or not. I followed the code described in the [docs](https://docs.revenuecat.com/docs/making-purchases).
Works perfectly on Android.
Tested on iPad, iOS 15.0.2.

Output of `flutter doctor`:
 ```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.454, on macOS 12.1 21C52 darwin-x64, locale it-IT)
    • Flutter version 2.9.0-1.0.pre.454 at /Volumes/Enrico HD/Devel/Flutter/Sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5e6945385c (28 hours ago), 2022-01-22 04:10:11 -0500
    • Engine revision 5b2068872a
    • Dart version 2.17.0 (build 2.17.0-45.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ecorradini/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (3 available)
    • macOS (desktop)         • macos                                    • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

From the logs it seems that the purchase succeeded:
```
[Purchases] - DEBUG: ℹ️ makePurchase
[Purchases] - DEBUG: 💰 Purchasing product from package  -  ....
[Purchases] - DEBUG: ℹ️ PaymentQueue updatedTransaction: .... 1000000954680062 ((null)) 1000000951108948 - 1
[Purchases] - DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/D5B17282-C4ED-4685-97A1-F802F9A55A3D/StoreKit/sandboxReceipt
[Purchases] - DEBUG: ℹ️ Found 0 unsynced attributes for App User ID: $RCAnonymousID:20e2a0c132264646a1bc0279f099915a
[Purchases] - DEBUG: ℹ️ There are no requests currently running, starting request POST /receipts
[Purchases] - DEBUG: ℹ️ API request started: POST /v1/receipts
[Purchases] - DEBUG: ℹ️ API request completed with status: POST /v1/receipts 200
[Purchases] - DEBUG: ℹ️ Serial request done: POST /receipts, 0 requests left in the queue
[Purchases] - DEBUG: 💰 Finishing transaction .... 1000000954680062 (1000000951108948)
```
However, `if(purchaserInfo.entitlements.all[productId]!.isActive)` fails.

Steps to reproduce, with a description of expected vs. actual behavior:
1. Purchase subscription (the user is subscribed, OK)
2. Cancel subscription (the user is not subscribed anymore, OK)
3. When the subscription has ended, re-subscribe (the user is subscribed with the new subscription, NO)

**Comment by beylmk** [comment] 2022-01-24 23:28
Hi @ecorradini thanks for the details! I just want to confirm the steps to reproduce. At the top of the description, you mention "Once disabled a subscription of a subscription group from the App Store page", but in the steps to reproduce you mention cancelling a subscription. Are those two separate cases, or were you describing the same thing?

Also, just to clarify -- you mentioned calling `purchaserInfo.entitlements.all[productId]!.isActive`. You would want to pass in the `entitlementID`, not the `productID`. Alternatively, you can call `purchaserInfo.entitlements.active` to get all of the active entitlements.

**Comment by ecorradini** [comment] 2022-01-25 15:38
Hey @beylmk. Yes, sorry for the ambiguity: with disable and cancel I mean the same thing, disable the subscription renewal.
productId is actually the entitlment, the variable name "productId" is a typo from when I used the in_app_purchases library. Everything works on Android, so I suppose the code is correct!

**Comment by beylmk** [comment] 2022-01-26 18:12
HI @ecorradini I don't have more info yet but wanted to update you that I'll be looking into this today!

**Comment by joshdholtz** [comment] 2022-01-26 23:30
I'll also be taking a look at this tomorrow as well!

**Comment by joshdholtz** [comment] 2022-01-28 15:24
@ecorradini I looked into this a tried everything I could to recreate and I was not able to 😔 

## The way I tested 
iPhone - iOS 15.3

1. Purchased a subscription in a subscription group (with a sandbox user)
2. Attempted to purchase subscription again but got alert saying "You're currently subscribed to this"
    - Wanted to do this step as a test  
2. Went to Settings -> App Store -> Sandbox User -> Manage and then cancelled my subscription
    - It appears that (with sandbox) that the sub ends instantly
3. Went back into Flutter app and I was able to purchased same subscription

## Follow up questions
1. Do your subscriptions have any introductory offers?
    - I'm curious if that might be the cause of something here
2. Have you tried on a newer version of iOS?
    - Apple has fixed quite a few bugs since 15.0.2 so might be worth updating to a newer OS if this is an Apple bug in their StoreKit subscription logic/caching
3. Is this the behavior that you are seeing after you cancel and try to resubscribe? 👇 Or are you seeing something different when you say that you aren't able to subscribe again?
![IMG_F045230C07B9-1](https://user-images.githubusercontent.com/401294/151573245-ff3bff71-2f94-4f0a-8274-3ad8ab52354d.jpeg)

Thanks!

**Comment by ecorradini** [comment] 2022-01-29 10:35
Hi @joshdholtz 
I made more tests and reproduced yours.
It works on iPhone with iOS 15.3.
I've updated iPad to iOS 15.3 and it works now.

**Comment by joshdholtz** [comment] 2022-01-31 15:23
@ecorradini Awesome, that's great to hear that things are working now! I wish there was something we could to help solve the 15.0.3 but it seems like its probably out of our control 😔 I'm going to close this issue but please let us know if there are any other issues you run into! Always happy to help get to the bottom of them 😊

**Closed by joshdholtz** 2022-01-31 15:23 UTC
Labels: bug, status: needs-additional-info
