### ISSUE TITLE
The item you are trying to buy has not been founds

### ISSUE THREAD

**Issue by HassanBalousha** [RevenueCat/purchases-flutter#91] opened 2020-08-23 07:43 UTC
The item you are trying to buy has not been found when purchasing a product

**Comment by aboedo** [comment] 2020-08-26 13:17
Hi! 👋  This sounds like there might be an issue with the testing user or play store config. 

Make sure that the user you're using to make purchases with has been added as a tester in the Play Store.

Here are our docs for getting this set up: https://docs.revenuecat.com/docs/google-play-store

**Comment by aboedo** [comment] 2020-08-26 13:19
If it has already been added as a tester, then a couple of things you might wanna try: 
- Make sure that you're logged into Play Store - open the app, and try downloading something that's free for example. 
- add a PIN to the device if one isn't present already
- we've had reports of folks who've had to add a valid credit card even though it's just for testing purposes.

**Comment by aboedo** [comment] 2020-08-26 14:41
@vegaro could this be related to https://github.com/RevenueCat/purchases-flutter/issues/93?

**Comment by rkotzy** [comment] 2020-10-14 23:00
This looks like a duplicate of: https://github.com/RevenueCat/purchases-flutter/issues/93

**Closed by rkotzy** 2020-10-14 23:00 UTC
Labels: bug
