### ISSUE TITLE
(IOS) Archive error

### ISSUE THREAD

**Issue by metarsul** [RevenueCat/purchases-flutter#134] opened 2020-12-06 20:07 UTC
Performed all the recommended steps like clearing pod cache, clean project, deleted derived data folder.

`flutter build ios`

> Building br.com.metarsul.appmetarsul for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXXXXX
Running pod install...                                             11,9s
Running Xcode build...                                                  
Compiling, linking and signing...                        79,6s
Xcode build done.                                           621,3s
Built /Users/rodrigo/APP/DEV/appmetarsul/build/ios/iphoneos/Runner.app.

` open ios/Runner.xcworkspace`
`Product -> Archive`

![image](https://user-images.githubusercontent.com/60826242/101291102-2a33ac00-37e5-11eb-9886-ecfb735a330b.png)

> /Users/rodrigo/APP/DEV/appmetarsul/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/RCPurchases+HybridAdditions.h:12:12: error: declaration of 'RCPurchases' must be imported from module 'Purchases' before it is required
@interface RCPurchases (HybridAdditions)
           ^

Tried several times, doing all steps mentioned in other bug reports

**Comment by metarsul** [comment] 2020-12-06 23:30
UPDATE:

Set iOS Deployment Target to 12.0, and it worked

**Comment by aboedo** [comment] 2020-12-07 14:12
I'm curious as to the solution: `purchases-flutter` only requires deployment target >= 9.0. 

@metarsul did you not have it set at all before? If so, there's a chance that what happened was: 
- cocoapods defaults to deployment target = 8.0
- cocoapods installation of our SDK fails because required deployment target is >= 9.0

and setting 12.0 would fix it. 
Could that have been the case here?

**Comment by rgusso** [comment] 2020-12-07 14:21
Yes, because the platform line was commented in my Podfile:
`#platform :ios, '5.0'`
so I set:
`platform :ios, '12.0'`

**Comment by aboedo** [comment] 2020-12-07 14:40
Cool, that's good to know. I'm closing this issue in that case, since this is expected behavior if the deployment target isn't set to iOS >= 9.0, [https://docs.revenuecat.com/docs/flutter#ios-deployment-target](as documented here). 

Thanks for following up!

**Closed by aboedo** 2020-12-07 14:40 UTC
Labels: bug

**Comment by ColeTownsend** [comment] 2021-03-23 22:30
This still occurs with iOS deployment target 11.0

**Comment by aboedo** [comment] 2021-03-26 18:46
@ColeTownsend there are quite a few things that could cause a very similar-looking error message. 
We're going to create a troubleshooting guide soon, but for the time being I'd recommend: 

- upgrading to the latest version of Flutter and `purchases-flutter`
- ensuring that Swift version is set to 5 in the project and in the Podfile
- ensuring that the deployment target is set in the project and in the Podfile
- running `rm -rf Pods` and then `pod install`
- cleaning derived data
