### ISSUE TITLE
Failed to connect to api.revenuecat.com

### ISSUE THREAD

**Issue by niypoo** [RevenueCat/purchases-flutter#196] opened 2021-05-19 11:14 UTC
After updated to `purchases_flutter: ^3.2.1`,
I found 188 non-fatal events in Android affecting 108 users in crashlytics, and I can't figure out where is the issue. 

**issue log 1**
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
PlatformException(10, Error performing request., {code: 10, message: Error performing request., readableErrorCode: NetworkError, readable_error_code: NetworkError, underlyingErrorMessage: Failed to connect to api.revenuecat.com/34.234.220.230:443}, null). Error thrown null.

StandardMethodCodec.decodeEnvelope (StandardMethodCodec.java:581)
MethodChannel._invokeMethod (MethodChannel.java:158)
Purchases.getOfferings (Purchases.java:123)
InAppPurchaseService.getCurrentProducts (InAppPurchaseService.java:66)
InAppPurchaseService.loadAllPurchasesItems (InAppPurchaseService.java:41)
```

**issue log 2*
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
PlatformException(10, Error performing request., {code: 10, message: Error performing request., readableErrorCode: NetworkError, readable_error_code: NetworkError, underlyingErrorMessage: Unable to resolve host "api.revenuecat.com": No address associated with hostname}, null). Error thrown null.
StandardMethodCodec.decodeEnvelope (StandardMethodCodec.java:581)
MethodChannel._invokeMethod (MethodChannel.java:158)
Purchases.getOfferings (Purchases.java:123)
InAppPurchaseService.getCurrentProducts (InAppPurchaseService.java:66)
InAppPurchaseService.loadAllPurchasesItems (InAppPurchaseService.java:41)
```

**issue log 3**
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
PlatformException(3, The device or user is not allowed to make the purchase., {code: 3, message: The device or user is not allowed to make the purchase., readableErrorCode: PurchaseNotAllowedError, readable_error_code: PurchaseNotAllowedError, underlyingErrorMessage: Billing is not available in this device. DebugMessage: Google Play In-app Billing API version is less than 3. ErrorCode: 3.}, null). Error thrown null.

StandardMethodCodec.decodeEnvelope (StandardMethodCodec.java:581)
MethodChannel._invokeMethod (MethodChannel.java:158)
Purchases.getOfferings (Purchases.java:123)
InAppPurchaseService.getCurrentProducts (InAppPurchaseService.java:66)
InAppPurchaseService.loadAllPurchasesItems (InAppPurchaseService.java:41)

```

<img width="935" alt="Screen Shot 2021-05-19 at 1 11 17 PM" src="https://user-images.githubusercontent.com/13227239/118803494-b45b6280-b8a3-11eb-94e9-ad4d84829d7d.png">

**Comment by vegaro** [comment] 2021-05-19 19:26
@niypoo It looks like those devices haven't been able to connect to our API but we haven't had any downtime lately. We haven't also made any change in the plugin that could lead to something like this.

The fact that the devices don't have play services installed makes me think it's actually not related to RevenueCat.

Are all the users using a similar device/OS? Are they rooted? Did you add any other plugin that could interfere with HTTP connection? Are you able to reproduce in your own device?

**Comment by niypoo** [comment] 2021-05-22 13:50
> @niypoo It looks like those devices haven't been able to connect to our API but we haven't had any downtime lately. We haven't also made any change in the plugin that could lead to something like this.
> 
> The fact that the devices don't have play services installed makes me think it's actually not related to RevenueCat.
> 
> Are all the users using a similar device/OS? Are they rooted? Did you add any other plugin that could interfere with HTTP connection? Are you able to reproduce in your own device?

Yes, I noticed that , this issue appearing when user us app without internet , so this issuer trigger from
```
PurchaserInfo purchaserInfo = await Purchases.getPurchaserInfo();
```

so what is best approach check internet before `Purchases.getPurchaserInfo` or this is normal approach!?

**Comment by aboedo** [comment] 2021-05-24 13:33
@niypoo you'll need to make sure that your code is prepared to handle exceptions when calling `getPurchaserInfo`, since the method can throw them. 

There's an example [in our docs](https://docs.revenuecat.com/docs/purchaserinfo#get-user-information): 
```dart
try {
  PurchaserInfo purchaserInfo = await Purchases.getPurchaserInfo();
  // access latest purchaserInfo
} on PlatformException catch (e) {
  // Error fetching purchaser info
}
```
I think there's room for improvement on our side in making this behavior clearer, since the [method declaration doesn't explicitly mention the possibility of an error](https://github.com/RevenueCat/purchases-flutter/blob/develop/lib/purchases_flutter.dart#L309). 

We''ll improve the docs to make it clearer

**Comment by aboedo** [comment] 2021-05-24 13:34
I'm tentatively closing this issue since this is expected behavior if network connectivity isn't available, but feel free to re-open if the solution above doesn't solve it, or open a new ticket if you run into more issues.

**Closed by aboedo** 2021-05-24 13:34 UTC
Labels: status: needs-additional-info

**Comment by niypoo** [comment] 2021-05-25 01:21
@aboedo  thanks , I did it as you suggested.
