### ISSUE TITLE
Unable to set Attributes - Same as #206

### ISSUE THREAD

**Issue by UlyssesAlves** [RevenueCat/purchases-flutter#383] opened 2022-06-17 23:06 UTC
- [x] I have updated Purchases SDK to the latest version (3.10.0)
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
I am using folloing code to update user name and email, but the changes don’t show up on Customer Profile page for this user on RevenueCat dashboard. Same as #206

```
Purchases.setDisplayName(“John Doe”);
Purchases.setEmail(“john@doe.com”);
```

![image](https://user-images.githubusercontent.com/2872102/174410937-b24cdc2b-92a2-42c3-a049-d19ca72af0ad.png)

Is this really the correct way to update user profile info?

**Comment by aboedo** [comment] 2022-06-20 12:48
Hey @UlyssesAlves, thanks for opening! 

The attributes are batched and synced when: 
- the app goes into the background
- the app goes into the foreground
- a purchase goes through

If you don't see the update, could you try minimizing the app and bringing it back to the foreground, then checking the dashboard?

**Comment by UlyssesAlves** [comment] 2022-06-20 15:59
@aboedo Thanks for replying.

I've tried all the three scenarios you suggested, but still the information attributes don't show up on RevenueCat dashboard.

A user has reported in [a thread on RevenueCat's Community](https://community.revenuecat.com/general-questions-7/adding-subscriber-attributes-1426#post5370):

> "I’m setting attributes via the REST API, and they show up when I hit the subscriber status endpoint, but they do not show up in the RevenueCat dashboard."

This suggests the problem may be on RevenueCat's Dashboard frontend code, which probably is not fetching the attributes and showing it on screen, even though these attributes do exist on the server.

**Comment by aboedo** [comment] 2022-06-20 16:12
🤔 that's definitely unexpected, thanks for reporting! We're investigating, I'll let you know when we know more

**Comment by UlyssesAlves** [comment] 2022-06-20 16:54
@aboedo I don't use RevenueCat's REST API in my app. I just need to set the user email and display name from the app directly into RevenueCat's Dashboard to help me track the user  without depending only on the user ID to identify the user.

I don't have a server setup for this, and I think it's not really necessary for my scenario, because I would be just redirecting the apps request to Revenue Cat's REST API, so it's simpler to just set the attributes directly with Revenue Cat's SDK.

**Comment by UlyssesAlves** [comment] 2022-06-20 20:03
@aboedo Sorry but I won't be able to do the test you ask for, because RevenueCat's Dashboard custommers listing is outdated and don't show my current users as expected.

I am currently making tests with some fictitious users. The first two users for which I had tested changing attributes for don't exist anymore in my system (I deleted them), so I deleted them also on Revenue Cat. These two users still show up on customers listing page on Revenue Cat dashboard, which I don't know why, since I deleted them.

Also, I have created new users, and I have just made a test purchase on Google Play Store. The purchase was made successul, but this new active user don't show up on Revenue Cat's dashboard.

So, since my current users aren't listed on Revenue Cat's dashboard, unfortunately I can't test changing nor fetching these users attributes, which is no better than the previous problem (showing the user without attributes). Actually, I will try fetching the user attributes. If this test works, it's because the user exist on server but is not being listed on RevenueCat Dashboard, right?

I don't know if these problems happen because I am still on sandbox/test mode, and I am not so sure if it will work OK after I publish my app in production. But I'll try the test you asked and share the results here afterwards.

**Comment by UlyssesAlves** [comment] 2022-06-20 20:12
@aboedo I am getting erros with the curl command:

C:\Users\ulysses.alves>curl --request 'GET' --url 'https://api.revenuecat.com/v1/subscribers/USERID' --header 'Accept: application/json' --header 'Authorization: Bearer sk_xxxxxxxxxxxxxxxxxxxxxxx' --header 'Content-Type: application/json'
curl: (1) Protocol "'https" not supported or disabled in libcurl
curl: (6) Could not resolve host: application
curl: (6) Could not resolve host: Bearer
curl: (6) Could not resolve host: sk_EElXUbUAOshzGakeSJaRHjeKfRFXK'
curl: (6) Could not resolve host: application

**Comment by UlyssesAlves** [comment] 2022-06-20 20:30
@aboedo Got the test working with Postman.

Yeah, the attributes are fetched correctly with REST API, like in the response fragment below:

```
"subscriber_attributes": {
            "$displayName": {
                "updated_at_ms": 1655684064461,
                "value": "Ulysses Alves"
            },
            "$email": {
                "updated_at_ms": 1655684064464,
                "value": "myemail@domain.com"
            }
        },
```

**Comment by aboedo** [comment] 2022-06-22 13:18
@UlyssesAlves thanks for getting back to us! 

We had some replication issues on Monday, which might explain the behavior you were seeing. Would you mind checking the dashboard again?

As for the missing purchases, please make sure that you have "View Sandbox Data" enabled, otherwise purchases that aren't from production won't show up. 

<img width="254" alt="image" src="https://user-images.githubusercontent.com/3922667/175038525-ad82cdc9-d9b1-427d-8512-8b070e859bca.png">

**Comment by UlyssesAlves** [comment] 2022-06-22 20:42
Yes, @aboedo . The name and email attributes are shown correctly now. This problem is solved.

**Comment by aboedo** [comment] 2022-06-24 18:26
Thanks for getting back to me @UlyssesAlves! 

I asked about the seemingly duplicate rows there: 
The view should be showing the users by appUserID, but if the `email` subscriber attribute has been set, it will display that instead. 

It should have a single row per user, though. Do they all list the same App User ID on this page? 
<img width="277" alt="image" src="https://user-images.githubusercontent.com/3922667/175642218-2c5c1f13-4fa7-43a7-b26f-eb87045b8103.png">

**Comment by UlyssesAlves** [comment] 2022-06-24 19:59
>Do they all list the same App User ID on this page?

Yes, @aboedo . They are the same user, listed twice.

Both of them, when clicked on, send me to the same URL, and thus the form Customer Profile shows exactly the same information for both of them.

**Comment by aboedo** [comment] 2022-06-24 20:03
Thanks for letting me know! I'm talking to the team for further clarification on that

**Comment by aboedo** [comment] 2022-06-27 18:44
@UlyssesAlves the team got back to me and confirmed the bug. It only happens for sandbox users, so you shouldn't run into anything odd in production. 
I'm tentatively closing this issue since the subscriber attributes are showing correctly now, but let me know if you run into any other issues!

**Closed by aboedo** 2022-06-27 18:44 UTC
Labels: bug

**Comment by UlyssesAlves** [comment] 2022-06-27 19:07
OK, @aboedo . There are no duplicated customers in my dashboard anymore, but the user attributes stopped updating again. 

I'll check this again after I publish my up. If the problem persists in production I'll report it.

Thanks.

**Comment by hasimyerlikaya** [comment] 2025-01-07 10:36
I have the same issue with Android.

I'm not able to set reserved attributes, but I am able to set custom attributes.

These methods are not working.

```
Purchases.setEmail(param.data.email);
Purchases.setDisplayName(param.fullName);
```

```
purchases_flutter: ^8.4.0

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.2 24C101 darwin-arm64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.96.2)
[✓] Connected device (6 available)
[✓] Network resources

```
