### ISSUE TITLE
How can I check that a subscriber's subscription has expired?

### ISSUE THREAD

**Issue by AlexShavkunov** [RevenueCat/purchases-flutter#174] opened 2021-03-17 22:46 UTC
As a test, I made a subscription on android, after which it expired, but when I check the data on the iOS, entitlementInfo still gives a value isActive is true, whereas field expirationDate is not relevant for two days already. Please tell me how you can check that the subscription has really expired? The only way is to check the data in expirationDate?

**Comment by vegaro** [comment] 2021-04-01 21:56
Thanks for opening. 

What you're doing is correct. You should check `isActive` to check if the entitlement is still active and you shouldn't worry about `expirationDate`. The entitlement should not show up as active in iOS after it expired in Android. It is possible that the entitlementInfo you were checking against and that still had `isActive` as `true` was a cached `entitlementInfo`. We check the date the `EntitlementInfo` was cached against the `expirationDate` to determine if the entitlement is active so users don't lose access if they have renewed but don't have connectivity.

Closing this since it's not a bug in our SDK and we are trying to keep GitHub Issues for bugs.

**Closed by vegaro** 2021-04-01 21:56 UTC
Labels: bug, status: needs-additional-info
