### ISSUE TITLE
Invalid product identifier

### ISSUE THREAD

**Issue by badranmo** [RevenueCat/purchases-flutter#106] opened 2020-09-28 11:40 UTC
I am  getting Invalid Product Identifiers , I am testing on a real device running IOS 14. I have checked all your article troubleshooting tips  : I have accepted the agreements, the product names are identical , the app is in testflight in status ready to submit , I have set a sandbox account and there is an identifier on the apple store connect for the app. I am on the latest package v 1.3.1 / flutter 1.20.4
I have also tried renaming products on both revenuecat and app store connect sides, no success.

 [Purchases] - DEBUG: Products request finished
[Purchases] - DEBUG: Valid Products:
[Purchases] - DEBUG: Invalid Product Identifiers -  "MY PRODUCT NAME"

Are there any issues with IOS 14 ? Any other things to check? 

Thanks

**Comment by rkotzy** [comment] 2020-09-28 18:28
On iOS 14 the StoreKit.config files aren't supported yet, but fetching products on a physical device from Apple should work. Other things to check in XCode is that the bundle Id is correct and the in-app purchase capability is added.

Going to close this out since it's not a reproducible SDK issue. If you need any other help here you can submit a ticket through the help center and our engineers can assist: https://support.revenuecat.com/hc/en-us

**Closed by rkotzy** 2020-09-28 18:28 UTC
Labels: bug
