### ISSUE TITLE
Can't identify user

### ISSUE THREAD

**Issue by davidmartos96** [RevenueCat/purchases-flutter#217] opened 2021-07-15 17:17 UTC
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/develop/CONTRIBUTING.md)
- [X] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
I'm trying to identify the logged in user (with Firebase) with the UID provided and I'm getting a Platform exception with the RevenueCat exception.

```
PlatformException(15, There was an unknown backend error., {
  code: 15, 
  message: There was an unknown backend error., 
  readableErrorCode: UnknownBackendError, 
  readable_error_code: UnknownBackendError, 
  underlyingErrorMessage: Backend Code: 7255 - Error creating subscriber alias.
}, null)
```

1. Environment
```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.58.0)
[✓] Connected device (3 available)

• No issues found!
```
2. Steps to reproduce: Sign in with Firebase, and in the `_firebaseAuth.userChanges()` stream, use the logged in user id as an identifier for the `Purchases.identify` function

**Additional context**
Tested device: Android 11 - Moto G5 Plus

**Comment by beylmk** [comment] 2021-07-15 18:57
Hey @davidmartos96 👋 sorry you're running into this...there are a number of reasons you could be getting this error, and without more info, I'm unable to pinpoint which it is.

Would you mind opening a support ticket, so that we can get more details about your app/account and track down the root cause? You can do that at support.revenuecat.com

**Comment by davidmartos96** [comment] 2021-07-15 18:59
Ok thanks! I'll do that

**Comment by beylmk** [comment] 2021-07-15 19:02
Great! I'll leave this issue open in case you need to follow up. Feel free to close it if the issue is addressed!

**Comment by davidmartos96** [comment] 2021-07-15 20:43
The problem was that the device used had more than the max 50 aliases allowed by the Revenue at backend. This is a test device with many reinstalls so I guess that could be true 😅

**Closed** 2021-07-15 20:44 UTC
Labels: bug

**Comment by rkotzy** [comment] 2021-07-15 20:45
Awesome! You should be able to delete that test customer from the RevenueCat dashboard to continue testing on that device.

**Comment by davidmartos96** [comment] 2021-07-15 20:59
Great, thanks again! Keep up the great work!
