### ISSUE TITLE
com.revenuecat.purchases.common.PurchasesPeriod.parse (PurchasesPeriod.java:125)

### ISSUE THREAD

**Issue by deadsoul44** [RevenueCat/purchases-flutter#68] opened 2020-06-17 12:20 UTC
Hello,

I started to see the following exception in Crashlytics logs in two devices (Huawei P30 lite, Android 9). How can I solve this? Thank you.

```
Fatal Exception: java.lang.RuntimeException: Text cannot be parsed to a Period: 365
       at com.revenuecat.purchases.common.PurchasesPeriod.parse(PurchasesPeriod.java:125)
       at com.revenuecat.purchases.common.MappersKt.mapPeriod(MappersKt.java:17)
       at com.revenuecat.purchases.common.MappersKt.mapIntroPrice(MappersKt.java:102)
       at com.revenuecat.purchases.common.MappersKt.map(MappersKt.java:101)
       at com.revenuecat.purchases.common.MappersKt.map(MappersKt.java:37)
       at com.revenuecat.purchases.common.MappersKt.map(MappersKt.java:63)
       at com.revenuecat.purchases.common.MappersKt.map(MappersKt.java:63)
       at com.revenuecat.purchases.common.CommonKt$getOfferings$2.invoke(CommonKt.java:7)
       at com.revenuecat.purchases.common.CommonKt$getOfferings$2.invoke(CommonKt.java:2)
       at com.revenuecat.purchases.ListenerConversionsKt$receiveOfferingsListener$1.onReceived(ListenerConversionsKt.java:7)
       at com.revenuecat.purchases.Purchases$fetchAndCacheOfferings$1$1$2.invoke(Purchases.java:10)
       at com.revenuecat.purchases.Purchases$fetchAndCacheOfferings$1$1$2.invoke(Purchases.java)
       at com.revenuecat.purchases.Purchases.dispatch(Purchases.java:60)
       at com.revenuecat.purchases.Purchases.access$dispatch(Purchases.java)
       at com.revenuecat.purchases.Purchases$fetchAndCacheOfferings$1$1.invoke(Purchases.java:46)
       at com.revenuecat.purchases.Purchases$fetchAndCacheOfferings$1$1.invoke(Purchases.java:2)
       at com.revenuecat.purchases.Purchases$getSkuDetails$1$1.invoke(Purchases.java:55)
       at com.revenuecat.purchases.Purchases$getSkuDetails$1$1.invoke(Purchases.java:2)
       at com.revenuecat.purchases.BillingWrapper$querySkuDetailsAsync$1$1.onSkuDetailsResponse(BillingWrapper.java:159)
       at com.android.billingclient.api.BillingClientImpl$10$1.run(BillingClientImpl.java:36)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by aboedo** [comment] 2020-06-17 14:20
hi! thanks for reporting. I believe this is a duplicate of https://github.com/RevenueCat/purchases-flutter/issues/40

**Comment by aboedo** [comment] 2020-06-17 14:22
I'm closing this one as a duplicate so that we can keep the conversation [on the original ticket](https://github.com/RevenueCat/purchases-flutter/issues/40)

**Closed by aboedo** 2020-06-17 14:22 UTC
