### ISSUE TITLE
The product is not available for purchase. | Error updating purchases. DebugMessage: . ErrorCode: ITEM_UNAVAILABLE.

### ISSUE THREAD

**Issue by drashoor** [RevenueCat/purchases-flutter#93] opened 2020-08-23 18:55 UTC
After a lot of tries, I failed to make a purchase.

Log:
```

W/ProxyBillingActivity(25585): Activity finished with resultCode 0 and billing's responseCode: 4
W/BillingHelper(25585): Couldn't find purchase lists, trying to find single data.
W/BillingHelper(25585): Received a bad purchase data.
W/BillingHelper(25585): Couldn't find single purchase data as well.
D/[Purchases] - DEBUG(25585): BillingWrapper purchases failed to update. DebugMessage: . ErrorCode: ITEM_UNAVAILABLE.null
W/[Purchases] - INFO(25585): Error updating purchases. DebugMessage: . ErrorCode: ITEM_UNAVAILABLE.
E/[Purchases] - ERROR(25585): The product is not available for purchase. | Error updating purchases. DebugMessage: . ErrorCode: ITEM_UNAVAILABLE.
W/FirebaseRemoteConfig(25585): No value of type 'String' exists for parameter key 'sessions_feature_enabled'.
D/FirebasePerformance(25585): Creating a new Non Verbose Session: edff62cca37b415f8ece228ad478cb47
W/FirebaseRemoteConfig(25585): No value of type 'String' exists for parameter key 'sessions_max_length_minutes'.
I/FIAM.Headless(25585): went foreground
I/FIAM.Headless(25585): Forcing fetch from service rather than cache. Test Device: false | App Fresh Install: true
I/FIAM.Headless(25585): Fetching campaigns from service.
W/FirebaseRemoteConfig(25585): No value of type 'String' exists for parameter key 'sessions_feature_enabled'.
W/DynamiteModule(25585): Local module descriptor class for providerinstaller not found.
I/ActivityThread(25585): com.google.android.gsf.gservices acquiringCount 2
I/DynamiteModule(25585): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/FirebaseRemoteConfig(25585): No value of type 'String' exists for parameter key 'sessions_max_length_minutes'.
W/ProviderInstaller(25585): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/FIAM.Headless(25585): Removing display event listener
W/FirebaseRemoteConfig(25585): No value of type 'String' exists for parameter key 'sessions_feature_enabled'.
I/sa.app.iStoria(25585): Background concurrent copying GC freed 59883(3MB) AllocSpace objects, 30(1176KB) LOS objects, 50% free, 5MB/10MB, paused 6.617ms total 211.683ms
I/FIAM.Headless(25585): Successfully fetched 0 messages from backend

```

**Comment by vegaro** [comment] 2020-08-25 00:47
Hi @drashoor,

Is your Play Store user a license tester and part of the testers of the closed track where you have published your debug app? You might find this article helpful https://docs.revenuecat.com/docs/google-play-store

**Comment by vegaro** [comment] 2020-08-26 00:06
Hi @drashoor 

I looked into it a little bit more and was able to reproduce it. It looks like Google has an open issue regarding this ([link to the issue](https://issuetracker.google.com/issues/155005449)).

I opened a PR that should fix it for Android https://github.com/RevenueCat/purchases-android/pull/183. Once that's released in Android we will update the Flutter plugin.

**Comment by reeichert** [comment] 2020-09-09 17:21
Hi guys, https://github.com/RevenueCat/purchases-android/pull/183 already merged, ther flutter plugin can be updated now?

**Comment by reeichert** [comment] 2020-09-11 14:36
@vegaro sorry to bother you, any update?

**Closed** 2020-10-14 22:57 UTC
Labels: Support

**Comment by gcostaapps** [comment] 2022-03-15 20:55
Is this issue back?

In my test user the purchase works well, but if it's not a test user I got a google play error that says `“This version of the application is not configured for billing through Google Play”` and these logs:


```
D/[Purchases] - DEBUG( 4247): ℹ️ Vending Offerings from cache
D/[Purchases] - DEBUG( 4247): 💰 Purchase started - product: com.revenuecat.purchases.models.ProductDetails@c2f3ed08 - offering: Cheap Test 1
D/[Purchases] - DEBUG( 4247): 💰 Purchasing product: mytime_yearly_7free_cheap1
D/[Purchases] - DEBUG( 4247): ℹ️ Checking if cache is stale AppInBackground false
W/BillingHelper( 4247): Couldn't find purchase lists, trying to find single data.
W/BillingHelper( 4247): Received a bad purchase data.
W/BillingHelper( 4247): Couldn't find single purchase data as well.
E/[Purchases] - ERROR( 4247): 🤖‼️ BillingWrapper purchases failed to update: DebugMessage: . ErrorCode: DEVELOPER_ERROR.null
E/[Purchases] - ERROR( 4247): 🤖‼️ One or more of the arguments provided are invalid.
I/flutter ( 4247): │ PlatformException(4, One or more of the arguments provided are invalid., {code: 4, message: One or more of the arguments provided are invalid., readableErrorCode: PurchaseInvalidError, readable_error_code: PurchaseInvalidError, underlyingErrorMessage: Error updating purchases. DebugMessage: . ErrorCode: DEVELOPER_ERROR., userCancelled: false}, null)
```

**Comment by vegaro** [comment] 2022-03-21 21:13
> but if it's not a test user I got a google play error that says “This version of the application is not configured for billing through Google Play”

@gcostaapps Are you testing in production with a non tester user? Can you please give more details? Also it would be better if you create a new issue, if you don't mind 😄 

Thanks!

**Comment by gcostaapps** [comment] 2022-03-23 20:39
Sorry @vegaro, I was running on flutter run in release mode, that's was the reason why it wasn't working. Running from the apk in the playstore did work.

**Comment by ProFive** [comment] 2023-07-08 05:44
When we upgraded to purchases_flutter: ^5.2.3 then app can not upgrade now 

I/flutter ( 7678): {} {2023-07-08 12:26:18.358000} {SubscriptionHelper} {paymentMultiSubscription purchasePackage chillaxdev_premium:yearly upgradeInfo oldProductIdentifier: chillaxdev_premium:monthly} {LogLevel.INFO}
D/[Purchases] - DEBUG( 7678): ℹ️ Vending Offerings from cache
D/[Purchases] - DEBUG( 7678): 💰 Product change started:  Subscription(productId=chillaxdev_premium, optionId=yearly, productDetails=ProductDetails{jsonString='{"productId":"chillaxdev_premium","type":"subs","title":"Premium Plan (ChillaxCare Dev)","name":"Premium Plan","description":"Premium Plan","localizedIn":["en-GB"],"skuDetailsToken":"AEuhp4KXq9Le04mGW9BWd7ltfdUSBajKOz3-VbxA3u4Ef55XBeXVgqtdGkkbJsyQxZAG","subscriptionOfferDetails":[{"offerIdToken":"AUj\/YhgIjKaPbI4nRZne0gJ+f2jHcLlg2bPG4wofLABdQ\/q77yg6CP4ZINKEEb+rsogwlWa5+aLITYzDiYals4hQb4+XN2HpD956b1LK5kFgTe3mXE\/k","basePlanId":"monthly","pricingPhases":[{"priceAmountMicros":142000000000,"priceCurrencyCode":"VND","formattedPrice":"₫142,000","billingPeriod":"P1M","recurrenceMode":1}],"offerTags":[]},{"offerIdToken":"AUj\/YhiaEy9PNh21uzjRV3FH+MeVEpMi9JXJSOp0r0ii+M11my90fCJbBsXze8jCzDV1iHT\/E77uIdE08vI09siybe55r8h4GXXPL+55k2VLo78=","basePlanId":"yearly","pricingPhases":[{"priceAmountMicros":1400000000000,"priceCurrencyCode":"VND","formattedPrice":"₫1,400,000","billingPeriod":"P1Y","recurrenceMode":1}],"offerTags":[]}]}', parsedJson={"productId":"chillaxdev_premium","type":"subs","title":"Premium Plan (ChillaxCare Dev)","name":"Premium Plan","description":"Premium Plan","localizedIn":["en-GB"],"skuDetailsToken":"AEuhp4KXq9Le04mGW9BWd7ltfdUSBajKOz3-VbxA3u4Ef55XBeXVgqtdGkkbJsyQxZAG","subscriptionOfferDetails":[{"offerIdToken":"AUj\/YhgIjKaPbI4nRZne0gJ+f2jHcLlg2bPG4wofLABdQ\/q77yg6CP4ZINKEEb+rsogwlWa5+aLITYzDiYals4hQb4+XN2HpD956b1LK5kFgTe3mXE\/k","basePlanId":"monthly","pricingPhases":[{"priceAmountMicros":142000000000,"priceCurrencyCode":"VND","formattedPrice":"₫142,000","billingPeriod":"P1M","recurrenceMode":1}],"offerTags":[]},{"offerIdToken":"AUj\/YhiaEy9PNh21uzjRV3FH+MeVEpMi9JXJSOp0r0ii+M11my90fCJbBsXze8jCzDV1iHT\/E77uIdE08vI09siybe55r8h4GXXPL+55k2VLo78=","basePlanId":"yearly","pricingPhases":[{"priceAmountMicros":1400000000000,"priceCurrencyCode":"VND","formattedPrice":"₫1,400,000","billingPeriod":"P1Y","recurrenceMode":1}],"offerTags":[]}]}, productId='chillaxdev_premium', productType='subs', title='Premium Plan (ChillaxCare Dev)', productDetailsToken='AEuhp4KXq9Le04mGW9BWd7ltfdUSBajKOz3-VbxA3u4Ef55XBeXVgqtdGkkbJsyQxZAG', subscriptionOfferDetails=[com.android.billingclient.api.ProductDetails$SubscriptionOfferDetails@92c1f1, com.android.billingclient.api.ProductDetails$SubscriptionOfferDetails@6fa31d6]}, token=AUj/YhiaEy9PNh21uzjRV3FH+MeVEpMi9JXJSOp0r0ii+M11my90fCJbBsXze8jCzDV1iHT/E77uIdE08vI09siybe55r8h4GXXPL+55k2VLo78=)  - offering: premium_plan_offer oldProductId: chillaxdev_premium:monthly googleProrationMode IMMEDIATE_WITHOUT_PRORATION
D/[Purchases] - DEBUG( 7678): ℹ️ Querying Purchase with chillaxdev_premium:monthly and type SUBS
D/[Purchases] - DEBUG( 7678): ℹ️ Checking if cache is stale AppInBackground false
E/[Purchases] - ERROR( 7678): 🤖‼️ PurchasesError(code=PurchaseInvalidError, underlyingErrorMessage=Couldn't find existing purchase for SKU: chillaxdev_premium:monthly, message='One or more of the arguments provided are invalid.')
I/flutter ( 7678): {} {2023-07-08 12:26:18.892000} {SubscriptionHelper} {paymentMultiSubscription: can't make payment PlatformException errorCode PurchasesErrorCode.purchaseInvalidError 4 -> One or more of the arguments provided are invalid.} {LogLevel.INFO}
