### ISSUE TITLE
Entitlements of Purchases.getPurchaserInfo() is empty when uninstall app

### ISSUE THREAD

**Issue by donchan922** [RevenueCat/purchases-flutter#146] opened 2021-01-22 04:28 UTC
## Steps to Reproduce
1. Use In-app products for Android (for remove Ads)
2. Purchase in app using `Purchases.purchasePackage(package)` (entitlements has values.)
3. Uninstall app
4. Install app
5. entitlements of `Purchases.getPurchaserInfo()`  is empty (it should has values such as subscription status.)

Is it bug or specifications?
I would not like to repurchase  In-app products for Android users, so I confirm subscription status before purchase.

**pubspec.yaml**
```yaml
purchases_flutter: ^2.0.0
```

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale ja-JP)
    • Flutter version 1.22.5 at /Users/donchan922/flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/donchan922/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

</details>

**Comment by aboedo** [comment] 2021-01-22 13:41
Hi! 
Once the app is uninstalled, the local information for RevenueCat is uninstalled as well. 
What you need to do is restore the subscription. You can do that either by using `identify` if you're using an account system (https://docs.revenuecat.com/docs/user-ids#provided-app-user-id), or by calling `restoreTransactions`. 
More information about this can be found [in our docs](https://docs.revenuecat.com/docs/making-purchases#restoring-purchases). 

We reserve GitHub issues for bug reports. I'm closing out this ticket since it's not a bug. Please check out our docs regarding restoring purchases to learn more about how to implement the behavior properly, and feel free to contact our support at https://support.revenuecat.com if you need more assistance afterwards.

**Closed by aboedo** 2021-01-22 13:42 UTC
Labels: bug
