### ISSUE TITLE
The subscription was successful without going through the payment process

### ISSUE THREAD

**Issue by thanhnhan111093** [RevenueCat/purchases-flutter#393] opened 2022-07-11 07:20 UTC
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

It happens only on ios
**Steps to reproduce:**
- Selected a subscription
- Tapped on "Upgrade now"
- Your app displayed a message that the subscription was successful without going through the payment process.

Apple rejected my app, and I reproduced it too.

Note: I attached the video clip, kindly look at once 
https://1drv.ms/v/s!AvJkkiWzYFLZgepeLsZflje_v7aEpQ

My Code

```dart
log("paymentMultiSubscription purchasePackage ${package.product.identifier} upgradeInfo oldSKU: ${upgradeInfo?.oldSKU}", name: tag);
          PurchaserInfo? purchaserInfo;
          if(Platform.isIOS){
            purchaserInfo = await Purchases.purchasePackage(package);
            latestPurchaserInfo = purchaserInfo;
            log("paymentMultiSubscription purchasePackage succeed for ios", name: tag);
          }else{
            purchaserInfo = await Purchases.purchasePackage(package, upgradeInfo: upgradeInfo);
            latestPurchaserInfo = purchaserInfo;
            log("paymentMultiSubscription purchasePackage succeed for android", name: tag);
          }

FirebaseHelper.getInstance().analyticAddToCart(
              itemCategory: offers[i].name ?? "",
              itemId: package.identifier,
              itemName: package.product.title,
              price: package.product.price,
              value: package.product.price,
              quantity: 12,
              currency: package.product.currencyCode);
          offers[i].isSelected = OfferDuration.none;
          activeSubscriptions = purchaserInfo.activeSubscriptions;
          activeEntitlementId = purchaserInfo.entitlements.active.keys.toList();
          log("paymentMultiSubscription purchasePackage succeed activeSubscriptions: $activeSubscriptions", name: tag);
          log("paymentMultiSubscription purchasePackage succeed activeEntitlementId: $activeEntitlementId", name: tag);
```

My Log 

```
{log} {2022-07-11 11:08:49.457000} {SubscriptionViewModel} {paymentMultiSubscription} {LogLevel.INFO} 
{log} {2022-07-11 11:08:49.460000} {SubscriptionViewModel} {paymentMultiSubscription basicOffer 1 addonOffer 0} {LogLevel.INFO} 
{log} {2022-07-11 11:08:49.462000} {SubscriptionHelper} {paymentMultiSubscription offers 1} {LogLevel.INFO} 
{log} {2022-07-11 11:08:49.464000} {SubscriptionHelper} {paymentMultiSubscription purchasePackage chillaxprod_premium.800.bs_monthly upgradeInfo oldSKU: null} {LogLevel.INFO} 
{log} {2022-07-11 11:08:49.479000} {FullScreenDialog} {initState============} {LogLevel.INFO} 
{log} {2022-07-11 11:08:53.911000} {SubscriptionHelper} {paymentMultiSubscription purchasePackage succeed for ios} {LogLevel.INFO} 
{log} {2022-07-11 11:08:53.912000} {SubscriptionHelper} {paymentMultiSubscription purchasePackage succeed activeSubscriptions: []} {LogLevel.INFO} 
{log} {2022-07-11 11:08:53.913000} {SubscriptionHelper} {paymentMultiSubscription purchasePackage succeed activeEntitlementId: []} {LogLevel.INFO} 
{log} {2022-07-11 11:08:53.913000} {SubscriptionHelper} {paymentMultiSubscription purchasePackage paySuccedName: [Premium Plan]} {LogLevel.INFO} 
{log} {2022-07-11 11:08:53.914000} {SubscriptionHelper} {paymentMultiSubscription: Succeed isVIP: false Beta: 1 isPremium false isPaidAddOn false} {LogLevel.INFO} 
```

log from console
```
default	13:44:24.031807+0700	ProjectName	[Purchases] - DEBUG: ℹ️ Vending Offerings from cache
default	13:44:24.032428+0700	ProjectName	[Purchases] - DEBUG: ℹ️ makePurchase
default	13:44:24.033031+0700	ProjectName	flutter: {log} {2022-07-12 13:44:24.027000} {SubscriptionViewModel} {paymentMultiSubscription} {LogLevel.INFO}
default	13:44:24.037729+0700	ProjectName	[Purchases] - DEBUG: 💰 Purchasing product from package  - prod_premium.800.bs_yearly in Offering premium_plan_offer
default	13:44:24.037866+0700	ProjectName	<SKPaymentQueue: 0x281f0a190>: Payment added for transaction already in the SKPaymentQueue: premium.800.bs_yearly
default	13:44:24.039674+0700	ProjectName	[Purchases] - DEBUG: ℹ️ PaymentQueue updatedTransaction: prod_premium.800.bs_yearly 2000000103041402 ((null)) 2000000062815972 - 1
default	13:44:24.106415+0700	ProjectName	flutter: {log} {2022-07-12 13:44:24.028000} {SubscriptionViewModel} {paymentMultiSubscription basicOffer 1 addonOffer 0} {LogLevel.INFO}
default	13:44:24.106511+0700	ProjectName	flutter: {log} {2022-07-12 13:44:24.028000} {SubscriptionHelper} {paymentMultiSubscription offers 1} {LogLevel.INFO}
default	13:44:24.106565+0700	ProjectName	flutter: {log} {2022-07-12 13:44:24.029000} {SubscriptionHelper} {paymentMultiSubscription i:0 package: Package(identifier: $rc_annual, packageType: PackageType.annual, product: Product(identifier: prod_premium.800.bs_yearly, description: 5Gen Care limited - Subscription plan, title: Premium plan, price: 59.9900016784668, priceString: $59.99, currencyCode: USD, introductoryPrice: null, discounts: []), offeringIdentifier: premium_plan_offer)} {LogLevel.INFO}
default	13:44:24.106595+0700	ProjectName	flutter: {log} {2022-07-12 13:44:24.029000} {SubscriptionHelper} {paymentMultiSubscription purchasePackag premium.bs_yearly upgradeInfo oldSKU: null} {LogLevel.INFO}
default	13:44:24.106661+0700	ProjectName	flutter: {log} {2022-07-12 13:44:24.043000} {FullScreenDialog} {initState============} {LogLevel.INFO}
default	13:44:24.114717+0700	ProjectName	[Purchases] - DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/8E784CF1-C592-4249-AC74-2818EE4AC785/StoreKit/sandboxReceipt
default	13:44:24.115040+0700	ProjectName	[Purchases] - DEBUG: ℹ️ Found 2 unsynced attributes for App User ID: 4590
default	13:44:24.116184+0700	ProjectName	[Purchases] - DEBUG: ℹ️ Unsynced attributes: {
    "$displayName" = "Subscriber attribute: key: $displayName value: nana setTime: 2022-07-12 06:44:01 +0000";
    "$email" = "Subscriber attribute: key: $email value: xxxxxxxx+13@gmail.com setTime: 2022-07-12 06:44:01 +0000";
}
default	13:44:24.129791+0700	ProjectName	[Purchases] - DEBUG: ℹ️ There are no requests currently running, starting request POST /receipts
default	13:44:24.129831+0700	ProjectName	[Purchases] - DEBUG: ℹ️ API request started: POST /v1/receipts
default	13:44:24.130700+0700	ProjectName	Task <DF20E59E-5B78-4685-85A1-30A38AE039E6>.<3> resuming, timeouts(60.0, 604800.0) QOS(0x21) Voucher (null)
default	13:44:24.131756+0700	ProjectName	[Telemetry]: Activity <nw_activity 12:2 [1C7867CA-193A-44A9-8CC8-A76C7B18BD97] (reporting strategy default)> on Task <DF20E59E-5B78-4685-85A1-30A38AE039E6>.<3> was not selected for reporting
default	13:44:24.131804+0700	ProjectName	Task <DF20E59E-5B78-4685-85A1-30A38AE039E6>.<3> {strength 0, tls 4, ct 0, sub 0, sig 1, ciphers 0, bundle 0, builtin 0}
default	13:44:24.131851+0700	ProjectName	Task <DF20E59E-5B78-4685-85A1-30A38AE039E6>.<3> now using Connection 29
default	13:44:24.458122+0700	ProjectName	Task <DF20E59E-5B78-4685-85A1-30A38AE039E6>.<3> sent request, body S 155079
default	13:44:24.812886+0700	ProjectName	Evaluating dispatch of UIEvent: 0x28280ee80; type: 0; subtype: 0; backing type: 11; shouldSend: 1; ignoreInteractionEvents: 0, systemGestureStateChange: 0
default	13:44:24.812954+0700	ProjectName	Sending UIEvent type: 0; subtype: 0; to windows: 1
default	13:44:24.813009+0700	ProjectName	Sending UIEvent type: 0; subtype: 0; to window: <UIWindow: 0x137d61e90>; contextId: 0xD2272222
default	13:44:24.813571+0700	ProjectName	Evaluating dispatch of UIEvent: 0x28280ee80; type: 0; subtype: 0; backing type: 11; shouldSend: 1; ignoreInteractionEvents: 0, systemGestureStateChange: 0
default	13:44:24.813592+0700	ProjectName	Sending UIEvent type: 0; subtype: 0; to windows: 1
default	13:44:24.813615+0700	ProjectName	Sending UIEvent type: 0; subtype: 0; to window: <UIWindow: 0x137d61e90>; contextId: 0xD2272222
default	13:44:24.813636+0700	ProjectName	Evaluating dispatch of UIEvent: 0x28280ee80; type: 0; subtype: 0; backing type: 11; shouldSend: 0; ignoreInteractionEvents: 0, systemGestureStateChange: 1
default	13:44:24.827126+0700	ProjectName	Evaluating dispatch of UIEvent: 0x28280ee80; type: 0; subtype: 0; backing type: 11; shouldSend: 1; ignoreInteractionEvents: 0, systemGestureStateChange: 0
default	13:44:24.827179+0700	ProjectName	Sending UIEvent type: 0; subtype: 0; to windows: 1
default	13:44:24.827231+0700	ProjectName	Sending UIEvent type: 0; subtype: 0; to window: <UIWindow: 0x137d61e90>; contextId: 0xD2272222
default	13:44:24.843775+0700	ProjectName	Evaluating dispatch of UIEvent: 0x28280ee80; type: 0; subtype: 0; backing type: 11; shouldSend: 1; ignoreInteractionEvents: 0, systemGestureStateChange: 0
default	13:44:24.843858+0700	ProjectName	Sending UIEvent type: 0; subtype: 0; to windows: 1
default	13:44:24.843947+0700	ProjectName	Sending UIEvent type: 0; subtype: 0; to window: <UIWindow: 0x137d61e90>; contextId: 0xD2272222
default	13:44:24.863910+0700	ProjectName	Evaluating dispatch of UIEvent: 0x28280ee80; type: 0; subtype: 0; backing type: 11; shouldSend: 1; ignoreInteractionEvents: 0, systemGestureStateChange: 0
default	13:44:24.863931+0700	ProjectName	Sending UIEvent type: 0; subtype: 0; to windows: 1
default	13:44:24.863957+0700	ProjectName	Sending UIEvent type: 0; subtype: 0; to window: <UIWindow: 0x137d61e90>; contextId: 0xD2272222
default	13:44:28.094371+0700	ProjectName	8.15.0 - [Firebase/Analytics][I-ACS023141] Purchase is a duplicate and will not be reported. Product ID: prod_premium.800.bs_yearly
default	13:44:28.784723+0700	ProjectName	[C29] event: client:data_stall @28.939s
default	13:44:29.065527+0700	ProjectName	Task <DF20E59E-5B78-4685-85A1-30A38AE039E6>.<3> received response, status 200 content K
default	13:44:29.066075+0700	ProjectName	Task <DF20E59E-5B78-4685-85A1-30A38AE039E6>.<3> done using Connection 29
default	13:44:29.067199+0700	ProjectName	Task <DF20E59E-5B78-4685-85A1-30A38AE039E6>.<3> response ended
default	13:44:29.068420+0700	ProjectName	Task <DF20E59E-5B78-4685-85A1-30A38AE039E6>.<3> summary for task success {transaction_duration_ms=4938, response_status=200, connection=29, reused=1, request_start_ms=0, request_duration_ms=328, response_start_ms=4936, response_duration_ms=1, request_bytes=155249, response_bytes=823, cache_hit=false}
default	13:44:29.069127+0700	ProjectName	Task <DF20E59E-5B78-4685-85A1-30A38AE039E6>.<3> finished successfully
default	13:44:29.069199+0700	ProjectName	[Purchases] - DEBUG: ℹ️ API request completed with status: POST /v1/receipts 200
default	13:44:29.072252+0700	ProjectName	<private>: Will add backgroundTask with taskName: <private>, expirationHandler: <__NSMallocBlock__: 0x2812206f0>
default	13:44:29.077058+0700	ProjectName	<private>: Created background task <private>. Assertion will be assigned soon
default	13:44:29.077620+0700	ProjectName	<private>: Creating new assertion since assertion is nil
default	13:44:29.078272+0700	ProjectName	<private>: Created new assertion <BKSProcessAssertion: 0x283e645a0>
default	13:44:29.078332+0700	ProjectName	<private>: Will add backgroundTask with taskName: <private>, expirationHandler: <__NSMallocBlock__: 0x281202520>
default	13:44:29.078382+0700	ProjectName	<private>: Created background task <private>. Assertion will be assigned soon
default	13:44:29.078454+0700	ProjectName	<private>: Reusing assertion <BKSProcessAssertion: 0x283e645a0>
default	13:44:29.080864+0700	ProjectName	[Purchases] - DEBUG: ℹ️ Serial request done: POST /receipts, 0 requests left in the queue
default	13:44:29.080992+0700	ProjectName	[Purchases] - INFO: ℹ️ Marking the following attributes as synced for App User ID: 4590: {
    "$displayName" = "Subscriber attribute: key: $displayName value: nana setTime: 2022-07-12 06:44:01 +0000";
    "$email" = "Subscriber attribute: key: $email value:xxxxxxxxx+13@gmail.com setTime: 2022-07-12 06:44:01 +0000";
}
default	13:44:29.084661+0700	ProjectName	<private>: Ending background task with UIBackgroundTaskIdentifier: 102
default	13:44:29.084768+0700	ProjectName	<private>: Ending task with identifier 102 and description: <private>, _expireHandler: <__NSMallocBlock__: 0x2812206f0>
default	13:44:29.084835+0700	ProjectName	<private>: Decrementing reference count for assertion used by background task with identifier 102: <private>
default	13:44:29.085927+0700	ProjectName	<private>: Ending background task with UIBackgroundTaskIdentifier: 103
default	13:44:29.086044+0700	ProjectName	<private>: Ending task with identifier 103 and description: <private>, _expireHandler: <__NSMallocBlock__: 0x281202520>
default	13:44:29.086111+0700	ProjectName	<private>: Decrementing reference count for assertion used by background task with identifier 103: <private>
default	13:44:29.086494+0700	ProjectName	[Purchases] - DEBUG: ℹ️ Sending updated PurchaserInfo to delegate.
default	13:44:29.086555+0700	ProjectName	<private>: Will invalidate assertion: <BKSProcessAssertion: 0x283e645a0> for task identifier: 103
default	13:44:29.086601+0700	ProjectName	[Purchases] - DEBUG: 💰 Finishing transaction prod_premium.800.bs_yearly 2000000103041402 (2000000062815972)
default	13:44:29.139755+0700	ProjectName	flutter: {log} {2022-07-12 13:44:29.098000} {SubscriptionHelper} {addPurchaserInfoUpdateListener from: 4590} {LogLevel.INFO}
default	13:44:29.167418+0700	symptomsd	Stall symptom detail: (symName/procName/ePid/ifIndex/interfaceType/stallType/endpoint/isFgOrBg): SYMPTOM_LIBNETCORE_DATA_STALL/ProjectName/29030/14/1/1/<private>/1
default	13:44:29.167532+0700	symptomsd	Stall symptom SYMPTOM_LIBNETCORE_DATA_STALL: ProjectName has preexisting endpoint match for stall type (1) within time range on interface type (1), updating timestamp: <private>
default	13:44:29.175146+0700	ProjectName	flutter: {log} {2022-07-12 13:44:29.100000} {SubscriptionHelper} {paymentMultiSubscription purchasePackage succeed for ios purchaserInfo (elderly_protection.overwrite.100.ao, access_control.overwrite.500.ao, premium_entitlement) } {LogLevel.INFO}
default	13:44:29.175271+0700	ProjectName	flutter: {log} {2022-07-12 13:44:29.100000} {SubscriptionHelper} {paymentMultiSubscription purchasePackage succeed activeSubscriptions: []} {LogLevel.INFO}
default	13:44:29.175622+0700	ProjectName	flutter: {log} {2022-07-12 13:44:29.100000} {SubscriptionHelper} {paymentMultiSubscription purchasePackage succeed activeEntitlementId: ()} {LogLevel.INFO}
default	13:44:29.175678+0700	ProjectName	flutter: {log} {2022-07-12 13:44:29.101000} {FePe App} {paymentMultiSubscription entitlements key:elderly_protection.overwrite.100.ao => value:EntitlementInfo(identifier: elderly_protection.overwrite.100.ao, isActive: false, willRenew: false, latestPurchaseDate: 2022-07-11T15:34:49Z, originalPurchaseDate: 2022-05-30T08:03:03Z, productIdentifier: protection_yearly, isSandbox: true, ownershipType: OwnershipType.purchased, store: Store.appStore, periodType: PeriodType.normal, expirationDate: 2022-07-11T16:34:49Z, unsubscribeDetectedAt: 2022-07-11T16:34:12Z, billingIssueDetectedAt: null) isActive:false identifier:elderly_protection.overwrite.100.ao } {LogLevel.INFO}
default	13:44:29.175771+0700	ProjectName	flutter: {log} {2022-07-12 13:44:29.101000} {FePe App} {paymentMultiSubscription entitlements key:access_control.overwrite.500.ao => value:EntitlementInfo(identifier: access_control.overwrite.500.ao, isActive: false, willRenew: false, latestPurchaseDate: 2022-07-08T12:53:54Z, originalPurchaseDate: 2022-04-28T09:18:22Z, productIdentifier: prod_access_notification_and_rejection.overwrite.100.ao_yearly, isSandbox: true, ownershipType: OwnershipType.purchased, store: Store.appStore, periodType: PeriodType.normal, expirationDate: 2022-07-08T13:53:54Z, unsubscribeDetectedAt: 2022-07-08T14:47:38Z, billingIssueDetectedAt: null) isActive:false identifier:access_control.overwrite.500.ao } {LogLevel.INFO}
default	13:44:29.175975+0700	ProjectName	flutter: {log} {2022-07-12 13:44:29.104000} {FePe App} {paymentMultiSubscription entitlements key:premium_entitlement => value:EntitlementInfo(identifier: premium_entitlement, isActive: false, willRenew: false, latestPurchaseDate: 2022-07-12T04:19:27Z, originalPurchaseDate: 2022-05-25T02:07:39Z, productIdentifier: prod_premium.800.bs_monthly, isSandbox: true, ownershipType: OwnershipType.purchased, store: Store.appStore, periodType: PeriodType.normal, expirationDate: 2022-07-12T04:24:27Z, unsubscribeDetectedAt: 2022-07-12T06:23:54Z, billingIssueDetectedAt: null) isActive:false identifier:premium_entitlement } {LogLevel.INFO}
default	13:44:29.176069+0700	ProjectName	flutter: {log} {2022-07-12 13:44:29.106000} {SubscriptionHelper} {paymentMultiSubscription purchasePackage succeed activeSubscriptions: []} {LogLevel.INFO}
default	13:44:29.176485+0700	ProjectName	flutter: {log} {2022-07-12 13:44:29.106000} {SubscriptionHelper} {paymentMultiSubscription purchasePackage succeed activeEntitlementId: []} {LogLevel.INFO}
default	13:44:29.176773+0700	ProjectName	flutter: {log} {2022-07-12 13:44:29.107000} {SubscriptionHelper} {paymentMultiSubscription purchasePackage failed activeSubscriptions not contains current product} {LogLevel.INFO}

```

**Comment by aboedo** [comment] 2022-07-11 17:19
Hey @thanhnhan111093 👋 Thanks for reporting! 

I'm having trouble trying to reproduce this. 
We did have a similar report for our react-native SDK, though:
https://github.com/RevenueCat/react-native-purchases/issues/358

In my testing, I did find some unexpected behavior in that sometimes when I try to re-purchase a product that I'm currently subscribed for, it gets marked as a success instead of an error. This seems to be a StoreKit bug and I'm filing a radar for it. 

The one difference in my testing vs your video is that I get a prompt by iOS saying "You're currently subscribed to this" which you don't seem to be getting. 

Does this happen to you with different sandbox users?

**Comment by beylmk** [comment] 2022-07-20 18:09
Hey @thanhnhan111093 looking back through the logs, I see `Payment added for transaction already in the SKPaymentQueue: premium.800.bs_yearly`, a log from StoreKit. This might be indicating that you're on a "dirty" sandbox account that has unfinished transactions. Our SDK calls to finish transactions, but sometimes sandbox behaves a little funny..

Can you try retesting with a fresh sandbox account?

**Comment by thanhnhan111093** [comment] 2022-07-21 02:32
> @thanhnhan111093 is there any pattern for when you can reproduce it? and just to confirm - are you handling potential exceptions thrown from purchasePackage?

In this case I don't see any exception.

**Comment by thanhnhan111093** [comment] 2022-07-21 02:39
> Hey @thanhnhan111093 looking back through the logs, I see `Payment added for transaction already in the SKPaymentQueue: premium.800.bs_yearly`, a log from StoreKit. This might be indicating that you're on a "dirty" sandbox account that has unfinished transactions. Our SDK calls to finish transactions, but sometimes sandbox behaves a little funny..
> 
> Can you try retesting with a fresh sandbox account?

We recreated a lot of Sandbox accounts to reproduce this scenario.

some accounts they have this error, and we can't buy that package again.

My Case:
Login Sandbox A and then buy premium in App Account A account, then wait for premium to expire. login App Account B to buy premium package

**Comment by beylmk** [comment] 2022-07-22 22:13
Hey @thanhnhan111093 I've tried again to reproduce these issues and unfortunately cannot :( 

Can you please provide all the code around the purchase? For instance, when do you display the "Thanks for your subscription" dialog? And where do you log `purchasePackage failed activeSubscriptions not contains current product` and `purchasePackage paySuccedName`?

I'll have a couple of other team members look at this with me on Monday.

**Comment by thanhnhan111093** [comment] 2022-07-25 07:19
here is my purchase code, i have update to check this case to show "Can't make payment"
```
  paymentMultiSubscription(BuildContext context, List<OfferingSettingModel> offers, Function? callback,
      {Function? onSubscriptionManageCallback}) async {
    _paying = true;
    log("paymentMultiSubscription offers ${offers.length}", name: tag);
    bool hasError = false;
    List<String> paySuccedName = [];
    List<String> activeSubscriptions =
        SubscriptionProvider.getInstance().current.purchaserInfo?.activeSubscriptions ?? [];
    List<String> activeEntitlementId =
        SubscriptionProvider.getInstance().current.purchaserInfo?.entitlements.active.keys.toList() ?? [];
    PurchaserInfo? latestPurchaserInfo;
    for (int i = 0; i < offers.length; i++) {
      CustomDialog.showLoadingDialogWithText(
          context, AppLocalizations.translate("Paying {package}").replaceAll("{package}", offers[i].name ?? ""));
      // CustomDialog.showLoadingDialog(context);
      Package? package;
      UpgradeInfo? upgradeInfo;
      if (offers[i].isSelected == OfferDuration.monthly) {
        package = offers[i].revenueCatOffer?.monthly;
      } else if (offers[i].isSelected == OfferDuration.yearly) {
        package = offers[i].revenueCatOffer?.annual;
      } else {
        continue;
      }

      //Handle upgrade/downgrade
        if (!TextUtil.isEmpty(offers[i].group) ) {// handle by group
          OfferingSettingModel? paid = current.settings?.offerings?.firstWhereOrNull((element) =>
          !TextUtil.isEmpty(element.entitlementId) && activeEntitlementId.contains(element.entitlementId));
          if (paid != null && paid.revenueCatOffer != null) {
            if (paid.id == offers[i].id) {
              String? monthlySubscription = offers[i].revenueCatOffer?.monthly?.product.identifier;
              if (!TextUtil.isEmpty(monthlySubscription) &&
                  activeSubscriptions.contains(monthlySubscription) &&
                  offers[i].isSelected == OfferDuration.yearly) { // handle same offer
                upgradeInfo = UpgradeInfo(monthlySubscription!);
              }
            } else if (activeSubscriptions.contains(paid.revenueCatOffer!.annual!.product.identifier)) {
              upgradeInfo = UpgradeInfo(paid.revenueCatOffer!.annual!.product.identifier, prorationMode: ProrationMode.immediateWithTimeProration);
            } else if (activeSubscriptions.contains(paid.revenueCatOffer!.monthly!.product.identifier)) {
              upgradeInfo = UpgradeInfo(paid.revenueCatOffer!.monthly!.product.identifier, prorationMode: ProrationMode.immediateWithTimeProration);
            }
          }
        } else if (offers[i].isSelected == OfferDuration.yearly) { // handle same offer
          String? monthlySubscription = offers[i].revenueCatOffer?.monthly?.product.identifier;
          if (!TextUtil.isEmpty(monthlySubscription) && activeSubscriptions.contains(monthlySubscription)) {
            //upgrade plan
            upgradeInfo = UpgradeInfo(monthlySubscription!);
          }
        }


      if (package != null) {
        try {
          log("paymentMultiSubscription purchasePackage ${package.product.identifier} upgradeInfo oldSKU: ${upgradeInfo?.oldSKU}", name: tag);
          PurchaserInfo? purchaserInfo;
          if(Platform.isIOS){
            try {
              PurchaserInfo _purchaserInfo = await Purchases.purchasePackage(package);
              // log("paymentMultiSubscription purchasePackage succeed for ios purchaserInfo ${_purchaserInfo.entitlements.all.keys} ", name: tag);
              log("paymentMultiSubscription purchasePackage succeed activeSubscriptions: ${_purchaserInfo.activeSubscriptions}", name: tag);
              log("paymentMultiSubscription purchasePackage succeed activeEntitlementId: ${_purchaserInfo.entitlements.active.keys}", name: tag);
              _purchaserInfo.entitlements.all.forEach((key, value) {
                log("paymentMultiSubscription entitlements key:$key => value:$value isActive:${value.isActive} identifier:${value.identifier} ");
              });
              // var _keyPremiumEntitlement = _purchaserInfo.entitlements.all['premium_entitlement'];
              // log("_keyPremiumEntitlement:$_keyPremiumEntitlement", name: tag);
              // if(_keyPremiumEntitlement != null && _keyPremiumEntitlement.isActive){
              //   log("Unlock that great <premium_entitlement> content", name: tag);
              // }
              latestPurchaserInfo = _purchaserInfo;
              purchaserInfo = _purchaserInfo.copyWith();
            } on PlatformException catch (e) {
              hasError = true;
              var errorCode = PurchasesErrorHelper.getErrorCode(e);
              log("paymentMultiSubscription: can't make payment PlatformException errorCode $errorCode ${e.code} -> ${e.message}", name: tag);
              await CustomDialog.dismissDialog(context);
              await CustomDialog.showDialogMessage(context,
                  message: "${offers[i].name ?? ""} - ${AppLocalizations.translate(e.message ?? "Can't make payment")}",
                  callbackYes: (){});
              break;
            }
            // purchaserInfo = await Purchases.purchasePackage(package);
          }else{
            purchaserInfo = await Purchases.purchasePackage(package, upgradeInfo: upgradeInfo);
            latestPurchaserInfo = purchaserInfo;
            log("paymentMultiSubscription purchasePackage succeed for android", name: tag);
          }
          offers[i].isSelected = OfferDuration.none;
          activeSubscriptions = purchaserInfo.activeSubscriptions;
          activeEntitlementId = purchaserInfo.entitlements.active.keys.toList();
          log("paymentMultiSubscription purchasePackage succeed activeSubscriptions: $activeSubscriptions", name: tag);
          log("paymentMultiSubscription purchasePackage succeed activeEntitlementId: $activeEntitlementId", name: tag);
          if(activeSubscriptions.contains(package.product.identifier)){ // check case payment succeed but don't  active subscription
            current.purchaserInfo = purchaserInfo;
            current.notifyListeners();
            paySuccedName.add(offers[i].name ?? "");
            log("paymentMultiSubscription purchasePackage paySucceedName: $paySuccedName", name: tag);
            CustomDialog.dismissDialog(context);
          }else{
            log("paymentMultiSubscription purchasePackage failed activeSubscriptions not contains current product", name: tag);
            CustomDialog.dismissDialog(context);
            await CustomDialog.showDialogMessage(context,
                message: "${offers[i].name ?? ""} - ${AppLocalizations.translate("Can't make payment")}",
                callbackYes: (){});
            break;
          }
        } on PlatformException catch (e) {
          hasError = true;
          var errorCode = PurchasesErrorHelper.getErrorCode(e);
          log("paymentMultiSubscription: can't make payment PlatformException errorCode $errorCode ${e.code} -> ${e.message}", name: tag);
          await CustomDialog.dismissDialog(context);
          await CustomDialog.showDialogMessage(context,
              message: "${offers[i].name ?? ""} - ${AppLocalizations.translate(e.message ?? "Can't make payment")}",
              callbackYes: (){});

          break;
        } catch (e){
          hasError= true;
          log("paymentMultiSubscription: can't make payment PlatformException $e", type: LogLevel.ERROR, name: tag);
          await CustomDialog.dismissDialog(context);
          await CustomDialog.showDialogMessage(context,
              message: "${offers[i].name ?? ""} - ${AppLocalizations.translate("Can't make payment")}",
              callbackYes: (){});
          break;
        }
      }
    }
    log("paymentMultiSubscription: Succeed isVIP: ${current.entitlement?.isVIP ?? false} Beta: ${current.betaPlan.length} isPremium ${current.isPremium} isPaidAddOn ${current.isPaidAddOn}", name: tag);

    CustomDialog.showLoadingDialog(context);
    try {
      latestPurchaserInfo = await Purchases.getPurchaserInfo();
    } on PlatformException catch (e) {
      log("paymentMultiSubscription: getPurchaserInfo $e", type: LogLevel.ERROR, name: tag);
      // Error fetching purchaser info
    }
    if(latestPurchaserInfo != null){
      await _changeCurrentPlan(latestPurchaserInfo, "paymentMultiSubscription");
    }
    log("paymentMultiSubscription: Sync Succeed isVIP: ${current.entitlement?.isVIP ?? false} Beta: ${current.betaPlan.length} isPremium ${current.isPremium} isPaidAddOn ${current.isPaidAddOn}", name: tag);

    CustomDialog.dismissDialog(context);
    _paying = false;
    if(paySuccedName.isNotEmpty){
      if(Platform.isAndroid){
        Purchases.restoreTransactions();
      }
      current.needRefreshSubscriptionInProfile = true;
      String succeedMessage = AppLocalizations.translate(
          "Thank you for subscription!\nYour subscription will be activated immediately.");
      if(hasError){
        succeedMessage += "\n";
        paySuccedName.forEach((element) {
          succeedMessage += "\n\u2022 $element";
        });
      }
      PaymentDialog.showDialog(context,
          message: succeedMessage,
          callback: callback);
    }
    log("paymentMultiSubscription versionName $versionName => ${current.settings?.requestUploadLogVersion}", name: tag);
  }
```

**Comment by beylmk** [comment] 2022-07-26 17:04
Hey @thanhnhan111093, thanks for the code! I'm a little confused... your initial logs are:

```
{log} {2022-07-11 11:08:53.912000} {SubscriptionHelper} {paymentMultiSubscription purchasePackage succeed activeSubscriptions: []} {LogLevel.INFO} 
{log} {2022-07-11 11:08:53.913000} {SubscriptionHelper} {paymentMultiSubscription purchasePackage paySuccedName: [Premium Plan]} {LogLevel.INFO} 
```
and that doesn't seem to match with the corresponding code, since `activeSubscriptions` are logged as empty and therefore `activeSubscriptions` should not return anything for `.contains`

```
log("paymentMultiSubscription purchasePackage succeed activeSubscriptions: $activeSubscriptions", name: tag);

          if(activeSubscriptions.contains(package.product.identifier)){ // check case payment succeed but don't  active subscription
            paySuccedName.add(offers[i].name ?? "");
            log("paymentMultiSubscription purchasePackage paySucceedName: $paySuccedName", name: tag);
```

Is that the check that you recently changed? if so, it'd be helpful to get updated logs.

Though I'm still thinking this could be a sandbox issue. A teammate recently mentioned that he ran into a sandbox quirk where he had to uninstall and reinstall the app before the app store receipt was empty of transactions, even AFTER switching sandbox accounts. I'm sorry this is such a frustrating issue, but could you try uninstalling and reinstalling the app after you switch sandbox accounts, and see if the issue persists?

**Comment by beylmk** [comment] 2022-07-26 17:28
Also can you please include your Purchases configuration code? Would love to see all of our purchases debug logs from time of app launch through the purchase.

**Comment by thanhnhan111093** [comment] 2022-07-27 02:00
> ```
> {log} {2022-07-11 11:08:53.913000} {SubscriptionHelper} {paymentMultiSubscription purchasePackage paySuccedName: [Premium Plan]} {LogLevel.INFO} 
> ```

you can ignore, we collect the package name, what the user buys

**Comment by thanhnhan111093** [comment] 2022-07-27 02:09
> Though I'm still thinking this could be a sandbox issue.

We thought so too, but we try again with pre-launch testing, and it still shows up

> but could you try uninstalling and reinstalling the app after you switch sandbox accounts, and see if the issue persists?

we tried, but it sometimes still happens, 10 sets of sandbox accounts will have 2 faulty sets (Report from my testing team)

> My Case:
> Login to Sandbox A and then buy premium in App Account A account, then wait for a premium to expire. login to App Account B to buy the Premium package


Currently, We have created to get the app approved to the store, I will continue to monitor and share the log with you

**Comment by beylmk** [comment] 2022-07-27 14:41
I'm so glad to hear it was approved! Please do keep us posted if you run into anything else. I'm going to close the issue for now, but feel free to re-open.

**Closed by beylmk** 2022-07-27 14:41 UTC
Labels: bug
