### ISSUE TITLE
Android: PurchasesErrorHelper.getErrorCode(e) returning wrong error for code 19 (paymentPendingError)

### ISSUE THREAD

**Issue by WieFel** [RevenueCat/purchases-flutter#222] opened 2021-07-22 19:46 UTC
**Describe the bug**
When purchasing a package in my flutter app, i want to handle the case for a pending purchase. Therefore, in the `try`-`catch` block that surrounds my `Purchases.purchasePackage(package)`, I want to check whether the returned error is a `paymentPendingError`. Complete code:
```dart
_purchase(Package package) async {
    try {
      PurchaserInfo purchaserInfo = await Purchases.purchasePackage(package);
      var isPurchased = purchaserInfo
          .entitlements.all[<MY_PRODUCT_ID>].isActive;
      if (isPurchased) {
        // Unlock that great "pro" content
      }
    } on PlatformException catch (e) {
      print(
          "PENDING ERROR: ${e.code} ${e.message} ${PurchasesErrorHelper.getErrorCode(e)}");
      // }
    }
  }
```

When completing a purchase with "Slow test card. Approves after a few minutes" in my Android app, I get the following error from RevenueCat debug log:
```
E/[Purchases] - ERROR(17202): 🤖‼️ The payment is pending.
```

The `print` statement I have added in the `catch` block yields the following:
```
I/flutter (17202): PENDING ERROR: 19 The payment is pending. PurchasesErrorCode.insufficientPermissionsError
```
It yields error code `19` and message `The payment is pending.`, which is correct. However, `PurchasesErrorHelper.getErrorCode(e)` yields the wrong error code `PurchasesErrorCode.insufficientPermissionsError` instead of the expected `PurchasesErrorCode.paymentPendingError`.

I think the mapping from number->error code is probably out of date. When counting through the `PurchasesErrorCode` enum, I get to index `20` for `paymentPendingError`, not `19`...

**Comment by beylmk** [comment] 2021-07-22 22:33
Hi @WieFel, great catch! You're totally right, our mappings are off by 1 after a certain point due to a previous refactor. Thanks for letting us know...expect a fix very soon.

**Comment by WieFel** [comment] 2021-07-23 05:48
Thanks @beylmk. Please let me know when the fix is published ;)

**Comment by aboedo** [comment] 2021-07-23 18:35
Hi @WieFel!! 👋  Thanks for reporting! 
I'm digging in and I made [this pr](#223), but I still haven't been able to reproduce this. 

Could you tell us SDK version you're using?

**Comment by WieFel** [comment] 2021-07-23 18:48
Hi @aboedo. I have been using v `3.0.0` previously, but I just updated to latest `3.4.0` and still experience the same issue.
The error object I catch in the `catch` clause is the following:
```
PlatformException(19, The payment is pending., {code: 19, message: The payment is pending., readableErrorCode: PaymentPendingError, readable_error_code: PaymentPendingError, underlyingErrorMessage: , userCancelled: false}, null)
```
Pending payment here is still error `19`, but inside the enum it is at index `20`.

Does your test of #223 succeed?

**Comment by aboedo** [comment] 2021-07-23 18:55
yeah, the test passes, so my guess is that the bug is somewhere else (still within the confines of `purchases-flutter` or `purchases-android`, which it's using under the hood). 

We'll continue digging and fix. Thanks for the quick reply!

**Comment by aboedo** [comment] 2021-07-29 17:28
update here: I found the underlying issue and created a fix PR for it https://github.com/RevenueCat/purchases-hybrid-common/pull/85

I'll keep the issue open until the fix has been released. 

Thanks once again @WieFel for opening!!!

**Comment by WieFel** [comment] 2021-07-29 17:40
@aboedo thank you very much! hope that the fix will be online soon

**Comment by aboedo** [comment] 2021-07-29 18:58
version 3.4.1 is out with the fix!! Closing this new, feel free to open a new issue if you run into anything else!!

**Closed by aboedo** 2021-07-29 18:58 UTC
Labels: bug
