### ISSUE TITLE
addPurchaserInfoUpdateListener not working properly 

### ISSUE THREAD

**Issue by officialFlutterDeveloper** [RevenueCat/purchases-flutter#250] opened 2021-09-25 12:28 UTC
im using the latest sdk 3.4.5

 im testing to get my grip on the package but im getting a little issues

basically I have one stful widget and in that widget I have an App bar and 1 button in centre 

in my INIT state I have used the following code

```dart
@override
void initState() {

  Purchases.addPurchaserInfoUpdateListener((purchaserInfo) {
    activeSubscriptions = purchaserInfo.entitlements.active.values.toList();

    print(activeSubscriptions.length);
    print(purchaserInfo.activeSubscriptions.length);
    setState(() {
      color = activeSubscriptions.isEmpty || activeSubscriptions == null
          ? Colors.red
          : Colors.green;
    });
  });
  super.initState();
  
}
```

im trying to make appBar color change depending on subscription state

 when I make a purchase and I get the successful prompt the app bar goes green so this works exactly how I want but when the expiration time ends it does not go back to red UNTIL the state is set again

**Comment by aboedo** [comment] 2021-09-28 14:37
Hi @officialFlutterDeveloper 👋 

I believe what's happening here would be caused by caching - the SDK caches the state of purchaserInfo for a few minutes (5 minutes when the app is in the foreground, longer if it's in the background). 

So when you make the purchase and go from inactive -> active, the status will reflect right away because the SDK is aware of the expiration. However, when you go from active -> expired, if the cache is still active, the value might not be updated right away. 

In practice in production, subscription durations are measured in days, not minutes, so 5 minutes is short enough that this would not be an issue. 

For sandbox testing, you can try: 
- after the subscription expired, waiting for a few minutes and then restarting the app, or minimizing it and bringing it back to the foreground should trigger a cache refresh. 

Hope this helps! Let me know if you have any more questions.

**Comment by officialFlutterDeveloper** [comment] 2021-09-28 14:42
thank you for explaining me I really appreciate it   I do have one more question  how do I upgrade and downgrade a subscription and have its status shown also is there an email I could ask you business related questions thanks :)

**Comment by aboedo** [comment] 2021-09-28 17:35
@officialFlutterDeveloper the best place for any questions is our [Community](https://community.revenuecat.com). There's a [guide in the Community](https://community.revenuecat.com/about-the-community-60/should-i-post-here-or-contact-revenuecat-support-78) that also provides further details on where to ask questions depending on what you're looking for. 

[This post on upgrades / downgrades](https://community.revenuecat.com/sdks-51/how-upgrades-downgrades-work-on-ios-and-android-217) also provides detail regarding how to use them. 

I'm closing this ticket for now, but let us know if you run into anything else!

Have a great day!

**Closed by aboedo** 2021-09-28 17:35 UTC
Labels: bug, status: needs-additional-info
