### ISSUE TITLE
Depracted Api error

### ISSUE THREAD

**Issue by jaybabani** [RevenueCat/purchases-flutter#231] opened 2021-08-10 12:36 UTC
Hello,

Get this error while trying to run "flutter build appbundle"

C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\purchases_flutter-3.4.1\android\src\main\java\com\revenuecat\purchases_flutter\PurchasesFlutterPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Please check.

**Comment by aboedo** [comment] 2021-08-10 17:04
hi @jaybabani!! Thanks for reporting! This is actually a duplicate of https://github.com/RevenueCat/purchases-flutter/issues/213, I'm closing this ticket out to keep the conversation in that one.

**Closed by aboedo** 2021-08-10 17:04 UTC
Labels: bug

**Comment by bryantgtx** [comment] 2023-10-28 21:18
The link to issue #213 is dead - is that conversation captured somewhere?
